### PR TITLE
Fixed terms slugging when creating through fieldtype

### LINKED ISSUE #7200: Term creation through fieldtype doesn't respect locale for slug
### Bug description

Creating a term normally through its taxonomy page will generate the correct slug, however creating the term through the fieldtype will result in the slug being generated with English.

The term `Kødpålæg` in Danish should generate the slug `koedpaalaeg`, but in English it's generated as `kodpalaeg`.

### How to reproduce

1. Create a site with Danish locale `da_DK`
2. Create a `tags` taxonomy
3. Create the term `Kødpålæg` in Danish and verify the slug is as stated above
4. Delete the term again
5. Create an entry with the taxonomy associated in Danish
6. Add `Kødpålæg` in the terms field without it existing
7. Save the entry and go to the tags taxonomy
8. Verify that the slug is wrongly generated as `kodpalaeg`

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: Comwell
Laravel Version: 9.42.2
PHP Version: 8.0.19
Composer Version: 2.1.5
Environment: local
Debug Mode: ENABLED
URL: comwell-v2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: mailgun
Queue: sync
Session: redis

Statamic
Addons: 3
Antlers: runtime
Version: 3.3.60 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 1.1.2
pecotamic/sitemap: 1.4.0
statamic/eloquent-driver: 1.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Fixes #7200

### CODE REVIEW

File: src/Fieldtypes/Terms.php [hunk 1]
```diff
@@ -373,7 +373,7 @@ public function usingSingleTaxonomy()
     protected function createTermFromString($string, $taxonomy)
     {
         $term = Facades\Term::make()
-            ->slug(Str::slug($string))
+            ->slug(Str::slug($string, '-', Site::selected()->handle()))
```
Comment (jasonvarga) [inline src/Fieldtypes/Terms.php:376]: You probably want `lang()` instead of `handle()`.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: src/Fieldtypes/Terms.php (hunk 1 above)
Comment (FrittenKeeZ) [reply src/Fieldtypes/Terms.php]: Yeah of course - fixed

**Review by jasonvarga — APPROVED** [review]
