### PR TITLE
Place entries in structure when localizing

### LINKED ISSUE #2471: Wrong parent when localizing an entry
## Bug Description

When editing an entry that's a child of another page, the "parent" field is correct.

When you swap to a secondary site, the "parent" field ends up incorrect. It uses the root.

## How to Reproduce

- Have multiple sites
- Have a root page, another top level page, and a child page:

  ```
  |-- Home
  |-- Another
       |-- A child
  ```

- Edit the child page
- Swap to another site (that the entry hasn't been localized into yet)

## Environment

**Statamic version:** 3.0.10

### PR DESCRIPTION
**Pull request by jasonvarga**
Fixes #2471 

Includes tests for what was already happening in there, plus new ones for the structure stuff.

### CODE REVIEW

File: src/Http/Controllers/CP/Collections/LocalizeEntryController.php [hunk 1]
```diff
@@ -14,11 +14,39 @@ public function __invoke(Request $request, $collection, $entry)
...
+            return;
+        }
+
+        // Collection not structured? Don't add it.
+        if (! $structure = $collection->structure()) {
+            return;
+        }
+
+        $tree = $structure->in($localized->locale());
+        $parent = $entry->parent()->in($localized->locale());
```
Comment (martindanielsson) [inline src/Http/Controllers/CP/Collections/LocalizeEntryController.php:40]: This breaks on pages with no parent
