### PR TITLE
Antlers runtime augment data collection values

### LINKED ISSUE #7426: Terms within a scoped collection don't augment
### Bug description

When you're looping a bunch of entries from a collection with attached terms, the terms don't augment when you scope the collection.

**This works**
```antlers
{{ posts }}
    <li>{{ title }}: {{ tags }}{{ title }} {{ /tags }}</li>
{{ /posts }}
```

**This doesn't work**
```antlers
{{ posts scope="post" }}
    <li>{{ post:title }}: {{ post:tags }}{{ title }} {{ /post:tags }}</li>
    {{ post:tags | dump }}
{{ /posts }}
```

You can see the difference in output here:
Screenshot 2023-01-30 at 11 06 11

This what you get when you dump the tags:
Screenshot 2023-01-30 at 11 06 30

### How to reproduce

1. Download this Statamic install: [test.zip](https://github.com/statamic/cms/files/10534645/test.zip)
2. Run `composer install`
3. Visit the homepage
4. Check `default.antlers.html` 

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.48.0
PHP Version: 8.1.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by JohnathonKoster**
This PR fixes #7426 by augmenting instances of `DataCollection` if they are returned from tag callbacks, allowing the following to "just work":

```antlers
{{ posts = { collection:blog } }}

{{ posts scope="post" }} {{ post:tags }} {{ title }} {{ /post:tags }} {{ /posts }}
```

### CODE REVIEW

File: src/View/Antlers/Language/Runtime/NodeProcessor.php [hunk 1]
```diff
@@ -1681,7 +1682,9 @@ public function reduce($processNodes)
                         $this->data = $lockData;
 
                         if (is_object($output)) {
-                            if ($output instanceof Collection) {
+                            if ($output instanceof DataCollection) {
+                                $output = RuntimeValues::resolveWithRuntimeIsolation($output);
+                            } elseif ($output instanceof Collection) {
                                 $output = $output->all();
```
Comment (jasonvarga) [inline src/View/Antlers/Language/Runtime/NodeProcessor.php:1688]: You could probably just avoid checking for DataCollection and just `resolveWithRuntimeIsolation` for regular Collection instances too.

The test passes. I'm just not sure if/when you'd ever _not_ want to do it. 🤔 

```suggestion
                            if ($output instanceof Collection) {
                                $output = RuntimeValues::resolveWithRuntimeIsolation($output);
```

Comment (JohnathonKoster) [reply src/View/Antlers/Language/Runtime/NodeProcessor.php]: I've made the change, and have added an extra sanity-check test in that file to ensure that tags returning `Collection` instances continue to work as intended.
