### PR TITLE
[4.x] Fix broken navigation tree

### LINKED ISSUE #9708: Navigation not viewable/editable via CP
### Bug description

Since updating to 4.53.0 when going into the Navigation section of CP and viewing a Nav the tree is not displayed.

Screenshot 2024-03-12 at 09 23 12

### How to reproduce

Update to 4.53.0 - go to Navigation and into a Nav.

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.47.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: conference.cica.com.au.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
mitydigital/iconamic: 1.1.6
mitydigital/statamic-google-fonts: 1.0.3
mitydigital/supportamic: 1.0.4
statamic/seo-pro: 5.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

Have tried this on several sites. Rolling back to 4.52.0 solves the issue.

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request fixes an issue where the navigation tree wouldn't load when attempting to edit a navigation, due to the `blueprints` prop not being passed in.

I've just ran into this myself after updating my site to the latest version.

Fixes #9708.
Caused by #9413.

### CODE REVIEW

File: resources/js/components/structures/PageTree.vue [hunk 1]
```diff
@@ -43,7 +43,7 @@
                     :is-open="page.open"
                     :has-children="page.children.length > 0"
                     :show-slugs="showSlugs"
-                    :show-blueprint="blueprints.length > 1"
+                    :show-blueprint="blueprints && blueprints.length > 1"
```
Comment (edalzell) [inline resources/js/components/structures/PageTree.vue:46]: `blueprints?.length` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
