### PR TITLE
[4.x] Fix duplicate entry action translation

### LINKED ISSUE #8938: Missing german translation for duplication action
### Bug description

The German translation is missing for the new feature that allows entries to be duplicated with their localizations.
The following translations are missing in the file `/resources/lang/en/messages.php`: 

- duplicate_action_warning_localization
- duplicate_action_warning_localizations
- duplicate_action_localizations_confirmation

image

### How to reproduce

1. Set the site locale to german: `'locale' => 'de',`
2. Create an entry
3. Duplicate entry by clicking on the three dots in the page tree of a collection

### Logs

_No response_

### Environment

```yaml
Statamic: version 4.32.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by jasonvarga**
Fixes #8938

The translator tool wasn't picking up the translation. Adding these comments fixes it.

### CODE REVIEW

File: src/Actions/DuplicateEntry.php [hunk 1]
```diff
@@ -36,9 +37,13 @@ public function confirmationText()
...
         if ($this->items->contains(fn ($entry) => $entry->hasOrigin())) {
-            return $this->items->count() === 1
-                ? 'duplicate_action_warning_localization'
-                : 'duplicate_action_warning_localizations';
+            if ($this->items->count() === 1) {
+                /** @translation */
+                return 'statamic::messages.duplicate_action_warning_localization';
+            } else {
+                /** @translation */
+                return 'statamic::messages.duplicate_action_warning_localizations';
```
Comment (edalzell) [inline src/Actions/DuplicateEntry.php:45]: use early return?
