### PR TITLE
[6.x] Fix Bard debounce race condition, Set move error, and Firefox scroll jumps

### LINKED ISSUE #13698: Pasted content in Bard editor disappears after quick text modification
### Bug description

When pasting content into the Bard editor, the pasted text can disappear immediately when quickly modifying existing text shortly before pasting.

Image

### How to reproduce

1. Open an entry with a Bard field
2. Ensure the following text already exists in the editor:

```plain
Lorem Ipsum is simply dummy text of the printing and typesetting indust. 
```
3. Delete the last two characters of the sentence
4. Re-type those two characters
5. Immediately paste some text from the clipboard (this needs to be done fairly quickly)
6. Observe that the pasted text disappears right after being inserted

### Logs

```shell

```

### Environment

```yaml
v6.0.0-beta.6
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #13772: Bard editor unstable: content loss, layout jumps, and disappearing nested fields
### Bug description

Bard field can become highly unstable during normal editing. This includes issues such as:

* Entire Bard content suddenly disappearing
* Nested Bard fields or sets vanishing from the editor
* The page jumping while typing
* UI overlaps occurring when adding Bard sets

These issues can happen when just typing text, moving / adding new sets.

Image

Image

Image

### How to reproduce

This is my Bard field config

```yaml
-
  handle: bard_field
  field:
    buttons:
      - h2
      - h3
      - bold
      - italic
      - unorderedlist
      - orderedlist
      - removeformat
      - quote
      - anchor
      - image
      - table
      - h1
      - h4
      - h5
      - h6
      - underline
      - strikethrough
      - small
      - superscript
      - subscript
      - code
      - codeblock
      - horizontalrule
      - alignleft
      - aligncenter
      - alignright
      - alignjustify
    container: assets
    remove_empty_nodes: false
    type: bard
    display: 'Bard Field'
    sets:
      new_set_group:
        display: 'New Set Group'
        sets:
          new_set:
            display: 'New Set'
            fields:
              -
                handle: bard_field
                field:
                  buttons:
                    - h2
                    - h3
                    - bold
                    - italic
                    - unorderedlist
                    - orderedlist
                    - removeformat
                    - quote
                    - anchor
                    - image
                    - table
                    - h1
                    - h4
                    - h5
                    - h6
                    - underline
                    - strikethrough
                    - small
                    - superscript
                    - subscript
                    - code
                    - codeblock
                    - horizontalrule
                    - alignleft
                    - aligncenter
                    - alignright
                    - alignjustify
                  container: assets
                  remove_empty_nodes: false
                  type: bard
                  display: 'Bard Field'
```

### Logs

```shell
Uncaught (in promise) RangeError: Position 1734 outside of fragment (<paragraph>)
    findIndex index.js:281
    nodeAt index.js:1340
    setNodeMarkup index.js:1130
    setNodeMarkup index.js:2067
    updateAttributes NodeView.ts:277
    command command.ts:21
    method CommandManager.ts:37
    updateAttributes NodeView.ts:270
    updateAttributes VueNodeViewRenderer.ts:89
    mounted Set.vue:336

---

Uncaught (in promise) TypeError: can't access property "getJSON", this.editor is null
    value BardFieldtype.vue:430
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    call runtime-core.esm-bundler.js:6251
    job reactivity.esm-bundler.js:1831
    flushPreFlushCbs runtime-core.esm-bundler.js:356
    updateComponentPreRender runtime-core.esm-bundler.js:5496
    componentUpdateFn runtime-core.esm-bundler.js:5415
    run reactivity.esm-bundler.js:237
```

### Environment

```yaml
6.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by o1y**
Fixes #13698
Fixes #13772

This addresses a few Bard issues:

1) Re-enable debouncing and fix race condition
As a workaround PR #13797 previously disabled debouncing. The debouncing issues were caused by the user editing content faster than the 150ms debounce delay (e.g. when deleting content and pasting new content). This adds a `cancel()` method to the debounce utility to cancel pending debounced updates before immediate updates, preventing stale content from overwriting fresh changes.

2) Fix type error when moving Sets
Moving Sets caused the error: `Uncaught (in promise) TypeError: can't access property "getJSON", this.editor is null`.

3) Fix scroll jumps in Firefox Browsers
The stylesheet changes introduced in #13750 caused Firefox to scroll to the top of the parent Bard field when clicking into nested Bard fields.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Woah, nice work! 🧙

File: resources/js/util/debounce.js [hunk 1]
```diff
@@ -14,4 +14,11 @@ export default function (func, wait, immediate) {
             if (!immediate) func.apply(context, args);
         }, wait);
     };
+
+    debounced.cancel = function () {
+        clearTimeout(timeout);
+        timeout = null;
+    };
+
+    return debounced;
```
Comment (jasonvarga) [inline resources/js/util/debounce.js:23]: It's blowing my mind a bit that `debounced` can be a function but can also have properties? wha?

Comment (o1y) [reply resources/js/util/debounce.js:23]: Haha, there are also some build in ones like `debounced.name`, `debounced.length` .. functions are objects :D
