### PR TITLE
#3241 - Adds &nbsp's for each paragraph rather than the last one

### LINKED ISSUE #3241: Widont modifier only affecting last paragraph with Bard
## Bug Description
A `&nbsp;` should be inserted between the final two words of _every_ paragraph. It is only functioning on the _last_ paragraph

## How to Reproduce
**1.** Bard field within a replicator with the following config:
```
-
  handle: block_text
  field:
    type: bard
    display: Text
    save_html: true
    buttons:
      - bold
      - italic
      - unorderedlist
      - orderedlist
      - html
      - anchor
      - h2
      - h3
      - removeformat
    listable: hidden
    always_show_set_button: false
    toolbar_mode: fixed
    link_noopener: false
    link_noreferrer: false
    target_blank: false
    reading_time: false
    fullscreen: true
    allow_source: true
```

2. Used within a partial view with: 
`{{ block_text | widont }}`

3. When two or more paragraphs are saved in the field, only the final paragraph receives the `&nbsp;`.
 
## Environment
**Statamic** 3.0.43 Pro
**Laravel** 6.20.16
**PHP** 7.4.9
**Addon** doublethreedigital/cookie-notice 3.0.5

**Install method**
Clone of previous site which originated from Cool Writings starter kit

### PR DESCRIPTION
**Pull request by berdjabrahamian**
Fixes #3241

Before
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```

After
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum&nbsp;ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend&nbsp;dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```

However, it doesnt take into consideration the params. Will push an update to add support for that.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Hey! From the looks of things, doesn't look your text to close the issue will work. Would you mind re-wording to `Closes #x` instead, that should work!

**Comment by berdjabrahamian** [comment]
Updated widont completely to utilize params as well - since we have noted it in the docs - as well as added tests for different variations.

**Comment by berdjabrahamian** [comment]
Im not sure why the tests are failing and what im missing

**Comment by jasonvarga** [comment]
I think it the `EOD`s needed their indentation removed. I updated that for you. Tests are running...

File: src/Support/Str.php [hunk 1]
```diff
@@ -165,27 +165,32 @@ public static function timeForHumans($ms)
...
             return str_replace('%###%##%', ' ', $value);
 
         // otherwise
         } else {
-            return preg_replace("/([^\s])\s+([^\s]+)\s*$/im", '$1&nbsp;$2', rtrim($value));
+            $value = preg_replace_callback("/([^\s]\s)([^\s]*\s?){{$params}}$/im", function ($matches) {
+                return preg_replace("/([\s])/", '&nbsp;', rtrim($matches[0]));
+            }, $value);
+
+            return $value;
```
Comment (jasonvarga) [inline src/Support/Str.php:193]: Can you just `return preg_replace_callback(...)`?

File: tests/Modifiers/WidontTest.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+
+    /** @test */
+    public function it_pases_bard_test()
+    {
+        $value = '<p>Lorem ipsum dolor sit amet.</p><p></p><p>Consectetur adipiscing elit.</p>';
+
+        $this->assertEquals('<p>Lorem ipsum dolor sit&nbsp;amet.</p><p></p><p>Consectetur adipiscing&nbsp;elit.</p>', $this->modify($value, 1));
+    }
+
+    public function modify($value, $params = 1)
```
Comment (jasonvarga) [inline tests/Modifiers/WidontTest.php:94]: Can you change this to `$params = []` so it tests no param by default?

**Review by jasonvarga — CHANGES_REQUESTED** [review]
A few small changes, but otherwise this is wonderful, thanks!

**Review by jasonvarga — APPROVED** [review]

**Comment by jasonvarga** [comment]
Thanks, very nice!
