### PR TITLE
[5.x] Support Laravel precognition on user forms

### LINKED ISSUE #6950: form validation not using the correct locale (`user:register_form`)
### Bug description

Form validation always uses the locale set in "config/app.php", instead of the correct locale based on "config/statamic/sites.php".

### How to reproduce

1. Setup a multisite
2. create and translate the localized error messages
3. submit form with error

### Logs

```shell
sites.php:

<?php

return [

    'sites' => [

        'de' => [
            'name' => config('app.name') .' - Deutsch',
            'locale' => 'de_DE',
            'url' => '/de/',
            'lang' => 'de',
        ],

        'en' => [
            'name' => config('app.name') .' - English',
            'locale' => 'en_US',
            'url' => '/',
            'lang' => 'en',
        ],

        'es' => [
            'name' => config('app.name') .' - Español',
            'locale' => 'es_ES',
            'url' => '/es/',
            'lang' => 'es',
        ],

        'zh' => [
            'name' => config('app.name') .' - 中国人',
            'locale' => 'zh_CN',
            'url' => '/zh/',
            'lang' => 'zh',
        ],

    ],
];






translation folder structure:

resources/lang/de/x.php
resources/lang/en/x.php
resources/lang/es/x.php
resources/lang/zh/x.php

all languages contain a translated validation.php
```

### Environment

```yaml
Statamic 3.3.47 Pro
Laravel 8.83.25
PHP 8.0.0
doublethreedigital/duplicator 2.3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_

### LINKED ISSUE #7890: Can't localise login:form errror/succes messages
### Bug description

I'm trying to localise the error and success message in `{{ user:login_form }}` but they remain English. I've tried to add the strings to my `nl.json` file but that doesn't seem to work. 

My _sites.php_:
```php
'sites' => [
    'default' => [
        'name' => config('app.name'),
        'locale' => 'nl_NL',
        'url' => '/',
    ],
],
```

Marco Rieser suggested to rename `nl.json` to `nl_NL.json` and add `'lang' => 'nl_NL'` to my default site. But that also doesn't work and it breaks all other localisable template strings.

### How to reproduce

Use `nl_NL` as a locale
Add a user login form
Add those strings to the nl.json file:

```json
"Invalid credentials.": "Ongeldige inloggegevens.",
"Login successful.": "Ingelogd.",
```

_Note:_ the field does get translated when I add it to `en.json` (but obviously it shouldn't pick up that one).

Or DM me for repo access.

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 9.52.5
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR adds support for [Laravel Precognition ](https://laravel.com/docs/10.x/precognition) to user forms (login, register, profile and password).

Again I've moved the validation logic out of the UserController and into separate [FormRequests](https://laravel.com/docs/10.x/validation#form-request-validation).

Closes #6950 
Closes #7890

### CODE REVIEW

**Comment by ryanmitchell** [comment]
@jasonvarga I've updated this now the main PR has merged. It should follow the same principles.

File: src/Http/Requests/UserRegisterRequest.php [hunk 1]
```diff
@@ -28,7 +28,7 @@ public function authorize(): bool
     protected function failedValidation(Validator $validator)
     {
         if ($this->isPrecognitive() || $this->wantsJson()) {
-            return (new ValidationException($validator))->errorBag($this->errorBag);
+            throw (new ValidationException($validator))->errorBag($this->errorBag);
```
Comment (ryanmitchell) [inline src/Http/Requests/UserRegisterRequest.php:31]: The reason I was using return rather than throw here and in the other requests is that it then gives the JSON response precognition expects rather than a standard response to a form (redirect in the failed test case). If you throw we'll need to build a response similar to how we do for `if ($this->ajax())`, but in the format Laravel expects:

```json
{
    "message": "The Email must be a valid email address.",
    "errors": {
        "email": [
            "The Email must be a valid email address."
        ]
    }
}
```

Comment (ryanmitchell) [reply src/Http/Requests/UserRegisterRequest.php]: Actually ignore that, I've found a different way to come at it. The issue was I wasn't actually sending a json request in the tests: https://github.com/ryanmitchell/cms/commit/04802e5391a24e99678dcb6962ead154b8cb77b5

Comment (jasonvarga) [reply src/Http/Requests/UserRegisterRequest.php]: When it was `return`ing it just wasn't working at all. No precognition errors were being shown.

Comment (ryanmitchell) [reply src/Http/Requests/UserRegisterRequest.php]: Yep - my most recent push fixes that.

Comment (jasonvarga) [reply src/Http/Requests/UserRegisterRequest.php]: Thanks!

**Comment by jasonvarga** [comment]
Just putting these here for the docs. When following our own forms docs for how to set up precognition, it explains we have to add an inner div with the precognition $form. Since the user tags don't have the whole js driver x-data thing, we can't grab the data off the `<form>` tag.

Instead, we can grab the values from `fields`.

```antlers
{{? $values = collect($fields)->mapWithKeys(fn ($field) => [
    $field['handle'] => $field['value']
]) ?}}

<div x-data='{
    form: $form(
        "post",
        $refs.form.getAttribute("action"),
        {{$ $values->toJson() $}}
    ).setErrors({{ error | json }}),
}'>
```

**Comment by ryanmitchell** [comment]
Thank you ❤️

**Comment by chatelardfrancois** [comment]
It seems custom error bags names for user login and password forms have'nt been integrated, wiil it be ?

**Comment by duncanmcclean** [comment]
Feel free to submit a PR if you need it yourself, or open a [feature request](https://github.com/statamic/ideas/issues).
