### PR TITLE
Remove duplicated array keys in fieldtype Code and Select

### LINKED ISSUE #5217: Duplicated array key in Select fieldtype
### Bug description

According to the docs, the fieldtype "Select"  has a [taggable option](https://statamic.dev/fieldtypes/select#options), but I don't see it on the CP. 

In the code I see that the config has two duplicate array keys with different values: https://github.com/statamic/cms/blob/master/src/Fieldtypes/Select.php#L62-L62

Looking back into the commit history, it looks like that the 2nd key is **the one**.

### How to reproduce

N/A

### Logs

_No response_

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by Konafets**
Closes #5217

### CODE REVIEW

File: src/Fieldtypes/Code.php [hunk 1]
```diff
@@ -57,7 +57,6 @@ protected function configFieldItems(): array
                     'xml' => 'XML',
                     'yaml-frontmatter' => 'YAML',
                 ],
-                'width' => 50,
```
Comment (jackmcdade) [inline src/Fieldtypes/Code.php:60]: Why is this line removed?

Comment (Konafets) [reply src/Fieldtypes/Code.php:60]: Because the key is defined already in line 32

**Review by jasonvarga — APPROVED** [review]
Maybe we meant to call the `taggable` option `Taggable`.

But, it's been `Allow additions` all this time, so this PR cleans up the code without any changes, technically. Perfect.
