### PR TITLE
[5.x] Handle entries in Link field with `is_external_url` modifier

### LINKED ISSUE #10072: `is_external_url` modifier breaks when an Entry is selected in a Link field
### Bug description

Related to https://github.com/statamic/cms/issues/10026, an exception is thrown when attempting to use the `is_external_url` modifier on a Link field.

The previous fix resolved entering a URL, however the issue still persists when an Entry is selected instead.

I've opened https://github.com/statamic/cms/pull/10071 with a potential fix.

### How to reproduce

1. On a fresh installation, add a Link field to the Page blueprint
2. Edit the _Home_ page and point the Link field to an Entry (not URL)
3. In layout.antlers.html, add the following:

```antlers
<a
    href="{{ link }}"
    target="{{ (link | is_external_url) ? '_blank' : '_self' }}"
>
    Link Text
</a>
```

### Logs
```
[2024-05-14 12:23:12] local.ERROR: str_starts_with(): Argument #1 ($haystack) must be of type string, Statamic\Entries\Entry given {"userId":"629be3ea-f10a-45e9-bdaf-4ce656a3067d","exception":"[object] (TypeError(code: 0): str_starts_with(): Argument #1 ($haystack) must be of type string, Statamic\\Entries\\Entry given at /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Support/Str.php:1494)
[stacktrace]
#0 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Support/Str.php(1494): str_starts_with(Object(Statamic\\Entries\\Entry), '/')
#1 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Support/Str.php(124): Illuminate\\Support\\Str::startsWith(Object(Statamic\\Entries\\Entry), Array)
#2 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Modifiers/CoreModifiers.php(1271): Statamic\\Support\\Str::isUrl(Object(Statamic\\Entries\\Entry))
#3 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Modifiers/Modify.php(197): Statamic\\Modifiers\\CoreModifiers->isExternalUrl(Object(Statamic\\Entries\\Entry), Array, Array)
#4 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Modifiers/Modify.php(154): Statamic\\Modifiers\\Modify->runModifier('is_external_url', Array)
#5 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Modifiers/Modify.php(131): Statamic\\Modifiers\\Modify->modify('is_external_url', Array)
#6 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/ModifierManager.php(121): Statamic\\Modifiers\\Modify->__call('is_external_url', Array)
#7 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1336): Statamic\\View\\Antlers\\Language\\Runtime\\ModifierManager::evaluate(Object(Statamic\\Fields\\Value), Object(Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment), Object(Statamic\\View\\Antlers\\Language\\Nodes\\Modifiers\\ModifierChainNode), Array)
#8 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1352): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->applyModifiers(Object(Statamic\\Fields\\Value), Object(Statamic\\View\\Antlers\\Language\\Nodes\\Modifiers\\ModifierChainNode))
#9 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1593): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->adjustValue(Object(Statamic\\Fields\\Value), Object(Statamic\\View\\Antlers\\Language\\Nodes\\VariableNode))
#10 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(947): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->getValue(Object(Statamic\\View\\Antlers\\Language\\Nodes\\VariableNode))
#11 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1564): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->process(Array)
#12 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(947): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->getValue(Object(Statamic\\View\\Antlers\\Language\\Nodes\\Structures\\SemanticGroup))
#13 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(321): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->process(Array)
#14 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(352): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluate(Array)
#15 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1197): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluateBool(Array)
#16 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(826): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluateTernaryGroup(Object(Statamic\\View\\Antlers\\Language\\Nodes\\Structures\\TernaryCondition))
#17 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(295): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->process(Array)
#18 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(318): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->processStatements(Array)
#19 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1914): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluate(Array)
#20 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#21 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#22 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('<!doctype html>...', Array)
#23 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/ammonitedigital/Site...', '<!doctype html>...', Array)
#24 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get('/Users/ammonitedigital/Site...', Array)
#25 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#26 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#27 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/View/View.php(123): Illuminate\\View\\View->render()
#28 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Responses/DataResponse.php(146): Statamic\\View\\View->render()
#29 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\\Http\\Responses\\DataResponse->contents()
#30 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Structures/Page.php(420): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#31 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#32 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#33 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#34 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#55 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#63 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#64 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#65 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#66 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/ammonitedigital/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/ammonitedigital/Sites/statamic/vendor/barryvdh/laravel-destatamicbar/src/Middleware/InjectDestatamicbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Destatamicbar\\Middleware\\InjectDestatamicbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#95 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#96 /Users/ammonitedigital/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1172): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#97 /Users/ammonitedigital/Sites/statamic/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#98 /Applications/Herd.app/Contents/Resources/valet/server.php(153): require('/Users/ammonitedigital/Site...')
#99 {main}
"} 
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.2.15
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by ammonitedigital**
This pull request fixes another issue with `is_external_url` - this time when an Entry is selected in a Link field, rather than a URL.

https://github.com/statamic/cms/issues/10026 was raised previously and fixed in https://github.com/statamic/cms/pull/10027

Fixes #10072.

### CODE REVIEW

**Review by duncanmcclean — APPROVED** [review]

File: src/Modifiers/CoreModifiers.php [hunk 1]
```diff
@@ -1268,6 +1269,10 @@ public function isExternalUrl($value)
             $value = $value->value();
```
Comment (jasonvarga) [inline src/Modifiers/CoreModifiers.php:1269]: I think we can just change this line to `$value = $value->url();` instead.

Comment (jasonvarga) [reply src/Modifiers/CoreModifiers.php]: Thanks but I mean without the entry condition.

Comment (ammonitedigital) [reply src/Modifiers/CoreModifiers.php]: Ah, gotcha. Tested locally and that's working great.

Comment (jasonvarga) [reply src/Modifiers/CoreModifiers.php]: Awesome, thanks!

**Review by jasonvarga — APPROVED** [review]
