### PR TITLE
[6.x] Prevent addon settings blueprints from being edited 

### LINKED ISSUE #12859: [6.x] Addon setting blueprint 404s
### Bug description

The nav to the addon's setting blueprint is a 404.

Image

The nav has `https://events.test/cp/blueprints/additional/events/settings/edit` as the link but that 404s

### How to reproduce

1) Have an addon w/ settings.
2) try to view the blueprint

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.35.1
PHP Version: 8.3.26
Composer Version: 2.8.11
Environment: local
Debug Mode: ENABLED
URL: events.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 6.0.0-alpha.14 Solo

Statamic Addons
transformstudios/events: dev-use-settings
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by duncanmcclean**
Right now, if an addon has a `resources/blueprints/settings.yaml` file, the blueprint will show as editable in the Control Panel.

This PR ensures that `settings.yaml` blueprints are filtered out when finding blueprints in a given namespace.

Closes #12859

### CODE REVIEW

File: src/Fields/BlueprintRepository.php [hunk 1]
```diff
@@ -299,7 +299,8 @@ protected function filesIn($namespace)
 
             $files = File::withAbsolutePaths()
                 ->getFilesByType($directory, 'yaml')
-                ->mapWithKeys(fn ($path) => [Str::after($path, $directory.'/') => $path]);
+                ->mapWithKeys(fn ($path) => [Str::after($path, $directory.'/') => $path])
+                ->reject(fn ($path) => Str::endsWith($path, 'settings.yaml'));
```
Comment (edalzell) [inline src/Fields/BlueprintRepository.php]: Shouldn't it check for ONLY that file name? In case someone has a blueprint called `duncan_settings.yaml`?
