### PR TITLE
[5.x] Improved JS slugs

### LINKED ISSUE #2817: Unable to generate slug with Chinese characters
## Bug Description
If you try to add Chinese characters in the Title field of an entry, Statamic doesn't generate the slug.

## How to Reproduce
1. In the Title field of an entry, insert: 你好，世界
2. Press "Save"

**Statamic version:** 3.0.25

**PHP version:** 7.4.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #9590: Slug: Single opening quotation mark in reference field converted to apostrophe (U+0027) for slug field
### Bug description

When using a single opening (English) quotation mark (‘) inside the slug reference field, the quotation mark is replaced with an apostrophe inside the slug field and a collection entry can't be posted (without modification) because the slug is invalid.

### How to reproduce

1. Create a new collection entry where slugs is used.
2. Type some random tekst together with the quotation mark (‘) in the slug reference field
3. In the slug field you'll see the apostrophe (U+0027)
4. Attempting to save the item will generate an error "The given data was invalid"
5. The full result from the call (HTTP 422):
`{
    "message": "The given data was invalid.",
    "errors": {
        "slug": [
            "May only contain letters, numbers, dashes and underscores."
        ]
    }
}`

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: <redacted>
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.7.1
Environment: production
Debug Mode: OFF
URL: <redacted>
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 20
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.45.0 PRO

Statamic Addons
oaked/statamic-resend-form-submissions: dev-master
rias/statamic-data-import: 1.3.0
rias/statamic-redirect: 3.6.1
roorda-ict/statamic-entries-export: 2.1.0
steets/statamic-addon-browser-lang-redirect: 0.1.8
steets/statamic-addon-extend-forms: 0.1.21
steets/statamic-addon-factory: 0.1.5
steets/statamic-addon-full-sitemap: 0.2.2
steets/statamic-addon-google-address: 0.1.8
steets/statamic-addon-mapbox-address: 0.1.5
steets/statamic-addon-markdown-text-field: 0.1.6
steets/statamic-addon-meilisearch: 0.1.1
steets/statamic-addon-permissions: 0.1.2
steets/statamic-addon-recaptcha: 0.2.2
steets/statamic-addon-responsive-images: 0.4.1
steets/statamic-addon-search-index-transformers: 0.2.9
steets/statamic-addon-steets-theme: 0.2.2
steets/statamic-addon-submit-button-field: 0.1.3
steets/statamic-addon-uuid: 0.1.3
steets/statamic-starter-kit: 0.1.15
```

### Installation

Starter Kit using via CLI

### Antlers Parser

Runtime (default)

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by duncanmcclean**
Edit by Jason:

The server side thing is good in theory but dealing with async stuff is a pain. So we've kept the JS version for when you need a quick slug like for handle, but you can use the server side thing when it's important language-aware ones like entry strings.

- Added `Statamic.$slug` JS API that generates slug fluently:
	- `Statamic.$slug.create('Foo Bar'); // foo-bar`
	- `Statamic.$slug.separatedBy('_').create('Foo Bar'); // foo_bar`
- Added `str_slug` and `snake_case` global helpers for these two cases. They mimic the naming of equivalent Laravel helpers.
	- `str_slug('Foo Bar'); // foo-bar`
	- `snake_case('Foo Bar'); // foo_bar`
- Server-side slug generation is opt in via new API.
	- This makes `.create()` return a promise.
	- It handles debouncing.
	- `Statamic.$slug.async().create('Foo Bar').then(slug => ...); // foo-bar`
	- `Statamic.$slug.async().separatedBy('_').in('zn').create('你好').then(slug => ...); // ni_hao`
- JS-based / speakingurl slugs are not removed. When you don't chain `async`, that's what's being used.
- The `<slugify>` component emits events so that you can track when slugification is happening.
- Appropriate components now show spinners when slug requests are happening.
	- Anywhere the `slug` fieldtype is used, like in entries.
	- When creating items like collections, navigations, forms, etc.

---

This pull request changes the way slugs are generated in the Control Panel. 

Until now, we've now used a library called `speakingurl`. It worked fine for generating slugs based on English strings but it didn't work so well for other languages, like [German](https://github.com/statamic/cms/issues/6985) & [Chinese](https://github.com/statamic/cms/issues/2817).

Rather than implementing another JS library, we've decided to generate the slugs using Laravel's [`Str::slug()`](https://laravel.com/docs/master/strings#method-str-slug) helper which seems to be more reliable with other languages.

We had made [some modifications](https://github.com/statamic/cms/blob/4.x/resources/js/plugins/slugify.js#L12-L19) to our `$slugify` helper to workaround issues like smart quotes, hiphens separated by spaces, etc. I've added tests for these cases and Laravel's string helper seems to handle them as expected.

Due to slug generation now being done on the server-side & needing to perform network requests, I've had to make changes to how we use the `$slugify` helper in various places across the codebase.

Closes #2817.
Closes #9590.

### CODE REVIEW

File: resources/js/components/blueprints/Sections.vue [hunk 1]
```diff
@@ -104,16 +104,23 @@ export default {
 
     methods: {
 
-        addSection() {
+        async addSection() {
+            let handle;
+            await this.$slugify(this.newSectionText, '_').then(slug => handle = slug);
+
+            console.log(handle);
```
Comment (jasonvarga) [inline resources/js/components/blueprints/Sections.vue:111]: 🪵

File: resources/js/components/blueprints/Sections.vue [hunk 2]
```diff
@@ -104,16 +104,23 @@ export default {
...
                 display: this.newSectionText,
                 instructions: null,
                 icon: null,
-                handle: this.$slugify(this.newSectionText, '_'),
+                handle: handle,
                 fields: []
             };
 
+            console.log(section)
+
```
Comment (jasonvarga) [inline resources/js/components/blueprints/Sections.vue:123]: 🪵

File: resources/js/plugins/slugify.js [hunk 3]
```diff
@@ -7,22 +7,11 @@ export default {
...
-
-            // Prevent `Block - Hero` turning into `block_-_hero`
-            custom[" - "] = " ";
-
-            return getSlug(text, {
-                separator: glue || '-',
-                lang,
-                custom,
-                symbols: Statamic.$config.get('asciiReplaceExtraSymbols')
+            return new Promise((resolve, reject) => {
```
Comment (jasonvarga) [inline resources/js/plugins/slugify.js:11]: Since the behavior of `$slugify` is changing to a promise, this PR should probably be targeting `master`.

File: tests/Feature/Fieldtypes/SlugTest.php [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    public function slugProvider()
+    {
+        return [
+            'single_word' => ['one', '-', 'en', 'one'],
+            'multiple_words' => ['one two three', '-', 'en', 'one-two-three'],
+            'apples' => ["Apple's", '-', 'en', 'apples'],
+            'smart_quotes' => ['Statamic’s latest feature: “Duplicator”', '-', 'en', 'statamics-latest-feature-duplicator'],
+            'highens_separated_by_spaces' => ['Block - Hero', '-', 'en', 'block-hero'],
+            'chinese_characters' => ['你好，世界', '-', 'ch', 'ni-hao-shi-jie'],
+            'german_characters' => ['Björn Müller', '-', 'de', 'bjoern-mueller'],
```
Comment (jasonvarga) [inline tests/Feature/Fieldtypes/SlugTest.php:42]: Can we throw an Arabic example in here? That's what really prompted this so we should make sure it's covered.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: tests/Feature/Fieldtypes/SlugTest.php (hunk 4 above)
Comment (jasonvarga) [reply tests/Feature/Fieldtypes/SlugTest.php:42]: I just grabbed a phrase from Google Translate. Good Morning in Arabic is `صباح الخير` 
If you pass it into `Str::slug` it outputs `sbah-alkhyr`. Plop that into the test using `ar`.👍 
We know it works, we just want to make sure it's in the test.

Comment (duncanmcclean) [reply tests/Feature/Fieldtypes/SlugTest.php:42]: Added!

The only reason I asked for one was the fact ChatGPT was giving me titles & slugs that didn't match up correctly so wanted a more realistic example.

**Review by jasonvarga — APPROVED** [review]
