### PR TITLE
Fix 500 errors for an empty search string

### LINKED ISSUE #2971: Searching for an empty string results in a 500 error
## Bug Description
A very low prio bug; but a bug nonetheless. When you search for something like a space in the CP, `Statamic/Search/Comb/Comb` throws a `Statamic\Search\Comb\Exceptions\NoQuery` exception. This is showing up in our error reporting, I think that this exception should be caught at controller level and return an empty result set instead.

## How to Reproduce
Search in the CP for an empty string (after trimming whitespace)

## Environment
Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.9

- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by jelleroorda**
Fixes #2971, this time staying inside the `Statamic\Search\Comb` namespace.

### CODE REVIEW

File: src/Search/Comb/Index.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ public function lookup($query)
 
         try {
             $results = $comb->lookUp($query)['data'];
-        } catch (NoResultsFound | NotEnoughCharacters $e) {
+        } catch (NoResultsFound | NotEnoughCharacters | NoQuery $e) {
```
Comment (jasonvarga) [inline src/Search/Comb/Index.php:29]: This class needs to be imported.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Thanks, an even better place than what I suggested in the other PR.

File: src/Search/Comb/Index.php (hunk 1 above)
Comment (jelleroorda) [reply src/Search/Comb/Index.php:30]: Good catch I've updated the PR.

**Comment by jasonvarga** [comment]
Thanks!
