### PR TITLE
Runtime: Improves recursive parent search

### LINKED ISSUE #6967: Antlers Runtime: Regression `recursive children` unpredictable
### Bug description

I'm printing a navigation multiple times on my site using the new Antlers runtime. When using `{{ *recursive children* }}` in combination with a condition around the `{{ nav }}`, it returns the children from a wrong {{ nav }} scope. Maybe this is a regression of #2712, a bug with the new runtime or I'm doing something completly wrong.

### How to reproduce

In the following example the second navigation will print the recursive children from the _first_ navigation.

_Workarounds_:
- remove the block `{{ if true }} ... {{ /if }}` 
- Add another inline condition inside, see comment below
- Change Antlers parser back to `regex`

```antlers {.lineNo}
 {{ nav handle="main_navigation" }}
  {{ if depth == 1 }}
    <div class="{{ if is_current || is_parent }}active{{ /if }}">
     <a href="{{ url }}">First: {{ title }}</a>
        {{ if children }}
      <ul>
        {{ *recursive children* }}
      </ul>
      {{ /if }}
    </div>
  {{ /if }}

  {{ if depth == 2 }}
    <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">First: {{ title }}</a></li>
  {{ /if }}
{{ /nav }}

{{ if true }} // this is just an example condition. removing it results in a correct recursive children return
  {{ nav handle="main_navigation" }}
    {{ if depth == 1 }}
      <div> // adding another inline if condition here results in returning the correct recursive children
        <a href="{{ url }}">Second: {{ title }}</a>
          {{ if children }}
        <ul>
          {{ *recursive children* }}
        </ul>
        {{ /if }}
      </div>
    {{ /if }}

    {{ if depth == 2 }}
      <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">Second: {{ title }}</a></li>
    {{ /if }}
  {{ /nav }}
{{ /if }}
```

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.30.1
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.49 PRO

Statamic Addons
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by JohnathonKoster**
This PR fixes #6967 by exiting the parent search early when it hits the closest `nav` tag.

Doing this will now work as expected:

```antlers
{{ nav handle="main" }}
    {{ if depth == 1 }}
        <div class="{{ if is_current || is_parent }}active{{ /if }}">
            <a href="{{ url }}">First: {{ title }}</a>
            {{ if children }}
                <ul>
                    {{ *recursive children* }}
                </ul>
            {{ /if }}
        </div>
    {{ /if }}
    {{ if depth == 2 }}
        <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">First: {{ title }}</a></li>
    {{ /if }}
{{ /nav }}

<hr />
{{ if true }}
    {{ nav handle="main" }}
        {{ if depth == 1 }}
            <div>
                <a href="{{ url }}">Second: {{ title }}</a>
                {{ if children }}
                    <ul>
                        {{ *recursive children* }}
                    </ul>
                {{ /if }}
            </div>
        {{ /if }}
        {{ if depth == 2 }}
            <li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">Second: {{ title }}</a></li>
        {{ /if }}
    {{ /nav }}
{{ /if }}
```

The included test case will also fail if the change is reverted.

### CODE REVIEW

File: src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php [hunk 1]
```diff
@@ -53,6 +53,12 @@ public static function associateRecursiveParent($nodes)
                         } else {
                             if (Str::contains($subNode->runtimeContent, $recursiveContent) && mb_substr_count($subNode->runtimeContent, '*recursive') == 1 && $node->getRootRef() == $subNode->getRootRef()) {
                                 $lastNode = $subNode;
+
+                                // Ensure we stop searching once we reach the closest nav parent.
+                                if ($subNode->name->name == 'nav') {
```
Comment (jasonvarga) [inline src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php:58]: Not that we have any other tag with recursion... but won't this only fix the `nav` tag specifically?

(I'm fine with this, though)

Comment (JohnathonKoster) [reply src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php:58]: Yea, this will be specific to the `nav` tag, unfortunately. I will do some more thinking on how to fix it a general way, but that will be a bit more challenging/difficult.

Comment (jasonvarga) [reply src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php:58]: That's okay, this is fine.
