### PR TITLE
[6.x] Update authorization / permissions

### LINKED ISSUE #8337: Can't use Nova, Telescope Gate in Laravel
### Bug description

i am currently trying to get Laravel Nova and Statamic to work with eloquent and after debugging for 5 hours I found one issue in the statamic AuthServiceProvider:

```
 Gate::before(function ($user, $ability) {
            return optional(User::fromUser($user))->isSuper() ? true : null;
        });
```

This `before` hook also overrides gates defined in Laravel Nova, Telescope, Horizion, ... 

Example of Novas default gate: 
```
 Gate::define('viewNova', function ($user) {
        return in_array($user->email, [
            'taylor@laravel.com',
        ]);
    });
 ```
 Can the before be wrapped in something to only be applied to statamics auth? 
 
        

### How to reproduce

If you need a demo repo with Statamic and Telescope for example I could set one up for you if needed.

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: HP
Laravel Version: 10.13.5
PHP Version: 8.1.18
Composer Version: 2.5.5
Environment: staging
Debug Mode: ENABLED
URL: cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.7.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

_No response_

### LINKED ISSUE #10832: Global `Gate::before()` checks affect Laravel policy checks outside of Statamic
### Bug description

A user reported that [these global Gate:: calls](https://github.com/statamic/cms/blob/5992f471a3f45eb22ee66cf4a7696775999bd398/src/Providers/AuthServiceProvider.php#L86-L96) affect Laravel policy checks outside of Statamic.

More specifically, this super user check will return `true` in policies outside of Statamic, which can lead to some unexpected behaviour when installing Statamic into existing Laravel apps...

```php
Gate::before(function ($user, $ability) {
    return optional(User::fromUser($user))->isSuper() ? true : null;
});
```

After some internal discussion, maybe we could look at a way to opt-out of these global Gate calls in favour of a middleware-based approach that can be selectively applied to routes / route groups?

Maybe that middleware-based approach becomes the new default in a major version as well (technically this is breaking change for anyone relying on these gates in addons, etc)?

Also, the above approach could work for normal web requests, but what about commands, jobs, etc.?

Related: #8337

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request:
- Only applies our auth logic to Statamic permissions, which prevents us from interfering with custom auth gates.
- Moves our auth logic from `Gate::before` to `after`, enabling users to more easily deny access to things.
- Adds super user checks to `before` in most Statamic policies to continue to avoid overhead when users are super.

Closes #8337.
Closes #10832.

### CODE REVIEW

File: src/Providers/AuthServiceProvider.php [hunk 1]
```diff
@@ -84,7 +85,13 @@ public function boot()
         });
 
         Gate::before(function ($user, $ability) {
-            return optional(User::fromUser($user))->isSuper() ? true : null;
+            Permission::boot();
```
Comment (duncanmcclean) [inline src/Providers/AuthServiceProvider.php:88]: While I think this approach is broadly on the right track, I don't really want to be booting permissions here... 

Although, I'm not sure what the best alternative is... 🤔
* Without booting permissions here, users can't access the CP because the `Authorize` middleware checks if the user has the relevant permissions, however it happens _before_ the `BootPermissions` middleware is called.
* We can't reorder the middleware, otherwise it might cause issues with translations in permission labels, which #7343 solved.

Comment (jasonvarga) [reply src/Providers/AuthServiceProvider.php:88]: What's wrong with booting in there? It only happens when the closure is executed.

Comment (duncanmcclean) [reply src/Providers/AuthServiceProvider.php:88]: I guess I was just thinking it was weird since we're already booting them in a middleware, and that trying to boot them multiple times would hurt performance?

Maybe I'm wrong though, and it's fine?

Comment (jasonvarga) [reply src/Providers/AuthServiceProvider.php:88]: We could make `Permissions::boot()` return early and do nothing if it's already been booted once.

File: src/Providers/AuthServiceProvider.php [hunk 2]
```diff
@@ -84,7 +85,13 @@ public function boot()
...
+
+            $isStatamicPermission = Permission::all()->first(fn ($permission) => $permission->value() === $ability);
+
+            if ($isStatamicPermission) {
+                return optional(User::fromUser($user))->isSuper() ? true : null;
+            }
         });
```
Comment (jasonvarga) [inline src/Providers/AuthServiceProvider.php:95]: I think we also discussed somewhere that our super check should probably be moved to `after`.

Otherwise, if someone wanted to override a gate/policy and explicitly deny the user (even if they are a super) they should be able to `return false`.

https://github.com/statamic/cms/issues/8337
