### PR TITLE
[6.x] Fix Firefox not receiving text selection in nested Bards

### LINKED ISSUE #13852: Cursor and text selection not working in nested Bard fields in Firefox
### Bug description

When using nested Bard editors in Firefox it is not possible to place the cursor or select text inside the nested Bard field. Mouse interactions inside the editor do not register. This issue already existed in v5 and seems to still be present in v6.

Some Workarounds
* Click a toolbar button twice, after which the editor becomes interactive
* Copy and paste the text again using Ctrl+C / Ctrl+V

Image

### How to reproduce

Add text in a nested Bard field

### Logs

```shell

```

### Environment

```yaml
Statamic 6.2.4
Firefox 147.0.3 (aarch64) macOS
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by jaygeorge**
## Description of the Problem

As per #13852, In Firefox, clicking inside a Bard field that is nested within another Bard field (e.g. Bard > Replicator > Bard) doesn't work properly. You cannot single-click to place the cursor or double-click to select a word. Triple-clicking to select a paragraph does work.

This is caused by [Firefox bug 739071](https://bugzilla.mozilla.org/show_bug.cgi?id=739071) (opened 13 years ago, WOW) — text selection doesn't work inside elements that have an ancestor with `draggable=true`. ProseMirror sets `draggable=true` on the Bard Set's node-view-wrapper element during initialization because the Set node spec has `draggable: true`. The existing workaround in the `updated()` hook resets this to `false`, but only on Vue re-renders — ProseMirror can set it back at any time in between.

## What this PR Does

- Fixes #13852
- Adds a `MutationObserver` in the Bard Set component's `mounted()` hook that watches the `draggable` attribute on the node-view-wrapper and immediately resets it to `false` whenever ProseMirror changes it. This ensures `draggable` never stays `true` long enough for Firefox's bug to prevent text selection in nested editors.

## How to Reproduce

1. Add text in a nested Bard field and try to highlight something in Firefox

### CODE REVIEW

File: resources/js/components/fieldtypes/bard/Set.vue [hunk 1]
```diff
@@ -330,12 +330,25 @@ export default {
...
+            }
+        });
+        this._draggableObserver.observe(this.$el, { attributes: true, attributeFilter: ['draggable'] });
     },
 
     updated() {
-        // This is a workaround to avoid Firefox's inability to select inputs/textareas when the
-        // parent element is set to draggable: https://bugzilla.mozilla.org/show_bug.cgi?id=739071
         this.$el.setAttribute('draggable', false);
     },
```
Comment (jasonvarga) [inline resources/js/components/fieldtypes/bard/Set.vue:348]: I think the `setAttribute` in `updated` is redundant now?

**Review by jasonvarga — CHANGES_REQUESTED** [review]

**Comment by jaygeorge** [comment]
Ah yes, Claude seems to think it's OK to remove that too. I re-tested the fix in Firefox and it still works fine.
