### PR TITLE
Slug languages

### LINKED ISSUE #2631: Slugs are not localized and uses different implementations
## Bug Description

I have noticed that that slugs for text's with danish national letters is converted wrongly. It seems like most things that use the toAscii function don't pass the short locale string. Only exception seems to be the slugify modifier which passes the short locale.

Also the code uses a ASCII implementation from both the Stringy class and from \Illuminate\Support\Str. Stringy seems to include an older implementation from Illuminate whom have replaced it with voku/portable-ascii. So slugify can return another result than other parts of the codebase.

The new implementation from voku/portable-ascii used by new versions of  \Illuminate\Support\Str is more complete as it covers more languages ( including danish )

In the Admin UI the library https://github.com/pid/speakingurl is used for generating slugs. It seems abandoned as it has not been updated for 3 years (plenty of issues/pr exist). Maybe there's a more complete and maintained library, but I have not found one.

A nice workaround would be the if we could add our extra transliterations in the specific project using the 'custom' option:

    slug = getSlug('Foo and Bar or Baz', {
	    custom: {
	        'and': 'und',
	        'or': ''
	    }
	});

## How to Reproduce
     
    <?php

    namespace App\Console\Commands;

    use Illuminate\Console\Command;
    use Statamic\Facades\Entry;
    use Statamic\Facades\Collection;

    class TestSlug extends Command
    {
        /**
         * The name and signature of the console command.
         *
         * @var string
         */
        protected $signature = 'test-slug';

        /**
         * The console command description.
         *
         * @var string
         */
        protected $description = 'Create entry with Danish title/slug';

        /**
         * Create a new command instance.
         *
         * @return void
         */
        public function __construct()
        {
            parent::__construct();
        }

        /**
         * Execute the console command.
         *
         * @return int
         */
        public function handle()
        {
            $title = 'Test med æøå';
            $collection = Collection::find('pages');
            $entry = Entry::make()
                    ->collection($collection)
                    ->slug($title)
                    ->data([
                        'title' => $title
                    ]);
        
                $entry->save();
        }
    }

This command creates a file with the name: 'test-med-aeoa.md'.

I can workaround this behaviour by using:

`->slug(Str::slug($attributes->title, '-', Config::getShortLocale()))`

which would produce a file with the name : 'test-med-aeoeaa.md'

## Environment

Statamic 3.0.16 Pro
Laravel 7.28.4
PHP 7.4.9
spatie/statamic-responsive-images 1.3.0

**Statamic version:** 3.0.16

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by jasonvarga**
Replaces #5291
Fixes #2631

- The `$slugify` plugin accepts a `lang`, and will fall back to the selected site, and then the default site.
- The `<slugify>` component can accept a `language` prop.
- The `<slug>` fieldtype gets the language of the entry being edited from the store.
- The Entry's `slug()` method will use its sites locale.
- Update tests now to include locales now that the slug method looks for the site.

### CODE REVIEW

File: src/Http/View/Composers/JavascriptComposer.php [hunk 1]
```diff
@@ -46,6 +47,7 @@ public function compose(View $view)
             'locale' => config('app.locale'),
             'permissions' => $this->permissions($user),
             'hasLicenseBanner' => $licenses->invalid() || $licenses->requestFailed(),
+            'charmap' => ASCII::charsArray(),
```
Comment (FrittenKeeZ) [inline src/Http/View/Composers/JavascriptComposer.php:50]: Will this support different dialects, like `fr_AT` over `fr`?

File: tests/Data/Entries/EntryTest.php [hunk 2]
```diff
@@ -74,9 +74,17 @@ public function it_sets_and_gets_the_slug()
     /** @test */
     public function the_slug_gets_slugified()
     {
+        Facades\Site::setConfig(['default' => 'en', 'sites' => [
+            'en' => ['locale' => 'en_US', 'url' => '/'],
+            'da' => ['locale' => 'da_DA', 'url' => '/da/'],
```
Comment (FrittenKeeZ) [inline tests/Data/Entries/EntryTest.php:79]: `da_DK` ;)

File: tests/Data/Entries/EntryTest.php [hunk 3]
```diff
@@ -74,9 +74,17 @@ public function it_sets_and_gets_the_slug()
...
+        ]]);
+
         $entry = new Entry;
-        $entry->slug('foo bar');
-        $this->assertEquals('foo-bar', $entry->slug());
+        $entry->slug('foo bar æøå');
```
Comment (FrittenKeeZ) [inline tests/Data/Entries/EntryTest.php:83]: `foo bar & æøå`

File: tests/Data/Entries/EntryTest.php [hunk 4]
```diff
@@ -74,9 +74,17 @@ public function it_sets_and_gets_the_slug()
...
+        $this->assertEquals('foo-bar-aeoa', $entry->slug());
```
Comment (FrittenKeeZ) [inline tests/Data/Entries/EntryTest.php:84]: `foo-bar-and-aeoa`

File: tests/Data/Entries/EntryTest.php [hunk 5]
```diff
@@ -74,9 +74,17 @@ public function it_sets_and_gets_the_slug()
...
+
+        $entry->locale('da');
+        $this->assertEquals('foo-bar-aeoeaa', $entry->slug()); // danish replaces æøå with aeoeaa
```
Comment (FrittenKeeZ) [inline tests/Data/Entries/EntryTest.php:87]: `foo-bar-og-aeoeaa`
Just to ensure special chars are accounted for

**Review by FrittenKeeZ — CHANGES_REQUESTED** [review]

**Comment by FrittenKeeZ** [comment]
@jasonvarga just some considerations - only `da_DK` is an actual error.

File: src/Http/View/Composers/JavascriptComposer.php (hunk 1 above)
Comment (jasonvarga) [reply src/Http/View/Composers/JavascriptComposer.php:50]: Yeah, looks like it.

image

File: tests/Data/Entries/EntryTest.php (hunk 2 above)
Comment (jasonvarga) [reply tests/Data/Entries/EntryTest.php:79]: I'll update it, but it's completely irrelevant for this test.

File: tests/Data/Entries/EntryTest.php (hunk 3 above)
Comment (jasonvarga) [reply tests/Data/Entries/EntryTest.php:83]: Ampersands weren't handled before this, they were just stripped out. I'll leave this change for another PR.

Illuminate\Support\Str::slug() strips them out.

Comment (FrittenKeeZ) [reply tests/Data/Entries/EntryTest.php:83]: Ahhh okay. They aren't stripped out through `slugify` though, that's why I thought it was the same for PHP.
image

Comment (jasonvarga) [reply tests/Data/Entries/EntryTest.php:83]: Oh Javascript. I see. 🤔  Okay then we can work something out in a separate PR/issue. Ideally I'd like the JavaScript to mimic the PHP.

**Comment by FrittenKeeZ** [comment]
Do you have any way to test the `slugify` function in javascript?

File: composer.json [hunk 6]
```diff
@@ -31,6 +31,7 @@
         "symfony/yaml": "^4.1 || ^5.1",
         "ueberdosis/html-to-prosemirror": "^1.3",
         "ueberdosis/prosemirror-to-html": "^2.6",
+        "voku/portable-ascii": "^1.2.3",
```
[the remark this answers is not in the document]
Comment (jasonvarga) [reply composer.json]: It wouldn't matter now, but they use 2.0 in Laravel 9, which will. Thanks!

**Comment by jasonvarga** [comment]
Yeah we have jest, but we can add a test for that later.

**Comment by FrittenKeeZ** [comment]
@jasonvarga I got a workaround for `&` :)
```diff
diff --git a/src/Support/Str.php b/src/Support/Str.php
index ef62b1870..e2b65eef9 100644
--- a/src/Support/Str.php
+++ b/src/Support/Str.php
@@ -4,6 +4,7 @@ namespace Statamic\Support;

 use Statamic\Facades\Compare;
 use Stringy\StaticStringy;
+use voku\helper\ASCII;

 /**
  * Manipulating strings.
@@ -15,6 +16,11 @@ class Str extends \Illuminate\Support\Str
         return call_user_func_array([StaticStringy::class, $method], $parameters);
     }

+    public static function ascii($value, $language = 'en')
+    {
+        return ASCII::to_ascii((string) $value, $language, false, true);
+    }
+
     /**
      * Creates a sentence list from the given $list.
      *
```

With this override, the test will pass:
```diff
diff --git a/tests/Data/Entries/EntryTest.php b/tests/Data/Entries/EntryTest.php
index ce3f768c4..653de9445 100644
--- a/tests/Data/Entries/EntryTest.php
+++ b/tests/Data/Entries/EntryTest.php
@@ -80,11 +80,11 @@ class EntryTest extends TestCase
         ]]);

         $entry = new Entry;
-        $entry->slug('foo bar æøå');
-        $this->assertEquals('foo-bar-aeoa', $entry->slug());
+        $entry->slug('foo bar & æøå');
+        $this->assertEquals('foo-bar-and-aeoa', $entry->slug());

         $entry->locale('da');
-        $this->assertEquals('foo-bar-aeoeaa', $entry->slug()); // danish replaces æøå wit
h aeoeaa
+        $this->assertEquals('foo-bar-og-aeoeaa', $entry->slug()); // danish replaces æøå
with aeoeaa
     }

     /** @test */
```

**Comment by FrittenKeeZ** [comment]
Alternatively, it can be configured through `config('statamic.sites.transliterate_symbols', true)`?

**Comment by jasonvarga** [comment]
Maybe, but I'd still like to keep the ampersand treatment separate from the rest of this PR.

**Comment by FrittenKeeZ** [comment]
I don't have anything else then :)
Ship it!
