### PR TITLE
Localize terms in the control panel

### LINKED ISSUE #3171: Translated taxonomies show up in the wrong language
## Bug Description

When having translated taxonomies, the dropdown selector shows the wrong language (they should be showing the `nl` site versions below, but the translations that are shown are from the `fr` site)

image

## How to Reproduce

- Multisite
- Have a collection with taxonomies
- Translate taxonomies in both sites
- See the wrong taxonomy translations in the dropdown

## Environment

Statamic 3.0.40 Pro
Laravel 7.30.4
PHP 8.0.0

### PR DESCRIPTION
**Pull request by riasvdv**
This fixes #3171

### CODE REVIEW

File: src/Fieldtypes/Terms.php [hunk 1]
```diff
@@ -209,6 +209,8 @@ protected function toItemArray($id)
             return $this->invalidItemArray($id);
         }
 
+        $term = $term->in(Site::current()->handle());
```
Comment (riasvdv) [inline src/Fieldtypes/Terms.php:212]: There doesn't seem to be any way to get the site from the request, but the current site (or the main one) is better than just the last one

**Comment by riasvdv** [comment]
Failing test is unrelated

**Comment by jasonvarga** [comment]
Glitch in the matrix. I re-ran the test workflow for you and it all passed.

File: src/Fieldtypes/Terms.php (hunk 1 above)
Comment (jasonvarga) [reply src/Fieldtypes/Terms.php:212]: Everything seems to work fine without the addition of this line. Is it required?

Comment (riasvdv) [reply src/Fieldtypes/Terms.php:212]: Yes, without this, I was getting the FR (second site) taxonomy translations displayed in the "already selected" taxonomies

image

With this it's the NL ones (first and default site).

Ideally it would show the NL translations on the NL version of the entry, and FR versions on the FR entry, but I couldn't find right away how to get that, so I opted that the current/default site was better.

Comment (jasonvarga) [reply src/Fieldtypes/Terms.php]: Thanks for confirming. I pushed a commit that'll get the locale from the entry, if you wanted to see how that's done.
