### PR TITLE
[6.x] Combobox 2.0

### LINKED ISSUE #1819: Combobox docs missing
The link linking to the combo box in this section

https://statamic.dev/getting-started/upgrade-guide/vue-2-to-3#removals

links to 

https://ui.statamic.dev/?path=/docs/components-combobox

### LINKED ISSUE #13615: [6.x] Combobox performance
### Bug description

The select takes quite a while to open. It get's worse when you instantly try to type in it as well. I am sure this is due to the amount of options listed, but it already has been working better in a prior beta.

### How to reproduce

https://github.com/user-attachments/assets/2f546d31-e718-48f5-8239-c02634605a6e

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: AGROPAC
Laravel Version: 12.48.1
PHP Version: 8.4.15
Composer Version: 2.8.11
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: database
Session: file

Storage
public/storage: NOT LINKED

Filament
Blade Icons: NOT CACHED
Packages: filament, forms, notifications, support, tables, actions, infolists, schemas, widgets
Panel Components: NOT CACHED
Version: v5.0.0
Views: NOT PUBLISHED

Livewire
Livewire: v4.0.2

Statamic
Addons: 4
Sites: 3 (Logistic, Spielwelten, Allgemein)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 6.0.0-beta.3 PRO

Statamic Addons
marcorieser/statamic-livewire: 5.2.0
schantldev/statamic-phosphoricons: dev-statamic-6
studio1902/statamic-peak-seo: dev-statamic-6
studio1902/statamic-peak-tools: dev-statamic-6
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #13704: Focus clipping in multisite dropdown
### Bug description

Image

### How to reproduce

see Screenshot above

### Logs

```shell

```

### Environment

```yaml
6.0.0-beta.6
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #13747: Combobox focus issues when `searchable="false"`
### Bug description

There seems to be a few focus state issues when `searchable="false"`:

* You can't tab to the combobox. 
* You can't press `space` or `enter` to open the combobox.
  * The event listeners for this are on the `<ComboboxInput>` component, but thats only rendered when the combobox is searchable.
* When you hover away from options in the dropdown, a focus state is visible. However, it's clipped on the left/right sides.

Originally reported as https://github.com/statamic/seo-pro/issues/487

### How to reproduce

1. Add a Select field to your blueprint
    * Make sure "Searchable" is disabled
2. Attempt to tab into the combobox. It won't work.
3. Open the dropdown and hover away. You'll see the clipped focus state.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.49.0
PHP Version: 8.4.17
Composer Version: 2.9.3
Environment: local
Debug Mode: ENABLED
URL: seo-pro-sandbox.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 6.x-dev PRO

Statamic Addons
statamic/seo-pro: 7.x-dev
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #13900: Select field with no options but "allow additions" is on, does not work as expected
### Bug description

in 5x, I used to have a "css class" select field inside a bard set.
This select field has no options predefined, but the "allow additions" is set to true. : 

Image

Image

Image

=> when clicking on the input, it loses focus, and there is no way to add any value inside.

If I provide one options in the blueprint, it works as expected... but I dont want any options by default.

Image

Image

Image

Image

Image

In 5x, it was working as expected, but in 6.2.5 it's not.

### How to reproduce

Just add a select field in any bard set with no default option, and the "allow additions" set to true. 

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 12.51.0
PHP Version: 8.4.13
Composer Version: 2.8.12
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: UTC
Locale: fr

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mariadb
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 6.2.5 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #14190: Dropdown values no longer in ascending order whilst searching
### Bug description

In v5 and below, numbered dropdown/select fieldtype values were sorted in ascending order during a search. They now seem to appear in random order.

`v6`:
Image
`< v6`:
Image

### How to reproduce

```yaml

-
  handle: numbers
  field:
    options:
      -
        key: 1980
        value: '1980'
      -
        key: 1991
        value: '1991'
      -
        key: 1992
        value: '1992'
      -
        key: 1993
        value: '1993'
      -
        key: 1994
        value: '1994'
      -
        key: 1995
        value: '1995'
      -
        key: 1996
        value: '1996'
      -
        key: 1998
        value: '1998'
      -
        key: 1999
        value: '1999'
      -
        key: 2000
        value: '2000'
    type: select
    display: Numbers
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.53.0
PHP Version: 8.5.0
Composer Version: 2.9.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Livewire
Livewire: v4.2.0

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 6.4.1 PRO

Statamic Addons
marcorieser/statamic-livewire: 5.2.1
statamic/seo-pro: 7.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #14241: Long text in a relationship field doesn't truncate
### Bug description

If you make a `Relationship` field and have a narrow field and long text, it overflows:

Image

### How to reproduce

1. make a relationship field
2. have long text in it
3. have the field be narrow

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Transform
Laravel Version: 12.54.1
PHP Version: 8.5.2
Composer Version: 2.9.3
Environment: local
Debug Mode: ENABLED
URL: transform.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Storage
public/storage: LINKED

Livewire
Livewire: v4.2.1

Statamic
Addons: 12
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 6.6.1 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.16.0
jacksleight/statamic-bard-mutator: 3.0.5
jacksleight/statamic-distill: 1.1.1
marcorieser/statamic-livewire: 5.2.1
statamic-rad-pack/typesense: 3.0.0
statamic/seo-pro: 7.2.0
transformstudios/events: 6.0-alpha.1
transformstudios/front: 3.1.2
transformstudios/github: dev-main
transformstudios/prime: dev-fix/v6-issues
transformstudios/review: 6.0.0-alpha.4
transformstudios/uptime: dev-prime
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #14389: Checkboxes - Default value with space
### Bug description

Options in `Checkboxes` fields may have a space in their keys.

Image

But it is not possible to type a space into the Default value field.
The only way to bypass this restriction is to paste the values into the field, which is how I managed to make the screenshot below. Saving is possible after doing so.
Image

On a related note, there is no auto-completion for the default values field, meaning a non-existing key could be typed in there. I am unsure what functionality that allows.

### How to reproduce

1. Add a checkboxes field in any blueprint
2. Add a key/label pair where the key has a space inside it (this step does not matter but if you do it, at least, you will rule out the possibility the space wasn't accepted because it does not match an existing key).
3. Try to type a default value with a space inside it

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 12.53.0
PHP Version: 8.3.6
Composer Version: 2.9.2
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Livewire
Livewire: v4.2.1

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 6.8.0 Solo

Statamic Addons
allyoullneed/inline-bard-components: dev-main
allyoullneed/statamic-forms: dev-main
alt-design/alt-seo: 1.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I tested pasting values with in a **Form** Blueprint and fields are correctly rendered in the form.
Test was done with a Statamic addon I will soon publish (wish me luck) but I have no reason to believe it may misbehave if using e.g. [dynamic rendering of fields](https://statamic.dev/tags/form-create#dynamically-rendering-fields) as values look well-formed.

I have not tested it in a collection blueprint but I suppose it works just as well.

AFAICT, default values in Radios fieldtype accept typing spaces, as they should.

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request overhauls the Combobox component to make it faster, more accessible, and less janky.

The current implementation grew slow and messy as we (mostly I) patched edge cases during alpha/beta. After researching how other component libraries handle certain things, I picked up some ideas for improving our own - and this PR is the result. 

There's a lot of changes in this PR, so I've tried to list everything I can remember:

## Dropdown width
The options dropdown was previously as wide as the longest option. This meant we needed to measure the options in JS (which impacted performance) and resulted in weirdly aligned dropdowns like this:

Pasted image 20260205111313 1

<p></p>

To keep things tidy, the dropdown is now fixed to the width of the trigger. This does, however, mean that long options may be truncated. 

I've adjusted the widths of comboboxes in a few places to account for this after looking through the Control Panel in German 🇩🇪.

CleanShot 2026-02-06 at 14 36 01

<p></p>

I've also added an `adaptiveWidth` prop which lets you opt-in to the old behaviour where necessary. We use this in the site selector to handle options with varying lengths.

Closes #13615

## Dropdown height & virtualization
Previously, the options dropdown would expand to fit the available space. 

For example: if the combobox was at the top of the page, and it contained a lot of options, it'd take up a large chunk of the screen:

CleanShot 2026-02-06 at 14 57 23

<p></p>

As [recommended by Reka](https://reka-ui.com/docs/guides/virtualization#usage), the dropdown now has a max height of 300px.

Adding a max-height has meant we're able to get rid of the hacky min-heights added in #13489 to prevent squished options when resizing the viewport.

It also means that Reka's virtualizer works properly, allowing us to ditch our custom `Scrollbar` component and rely on the browser's scrollbar. 🎉

## Other improvements
* Fixed keyboard accessibility issues when `searchable="false"`
  * Fixes #13747
* Fixed focus clipping and `z-index` issue with the header site selector
  * Fixes #13704
* Opening the dropdown will now scroll to the selected option 
* The search query is now cleared when closing the dropdown
* Search results are now returned in the original order, rather than fuzzsort's relevance order
  * Fixes #14190
* Added an `align` prop to determine the alignment of the dropdown
* The non-searchable state now renders the `<input>`, but it's read-only
* Improved how we handle "taggable" comboboxes
  * Fixes #13900
* Fixed issue when selecting options in relationship typeahead
  * When you've partially typed an option and click it in the dropdown, the blur event would be triggered, causing the partially typed option to be added instead of the one you clicked.
* Added truncation to the selected option in the relationship fieldtype's select mode
  * Fixes #14241
* Fixed issue where pressing space in the `ComboboxInput` wouldn't actually give you a space. 
  * This was due to the `@keydown.open` listener on the `ComboboxTrigger`. Fixed by preventing typing in the input from cancelling the input event.
  * Fixes #14389
* Added browser tests & documentation with Storybook
  * Closes https://github.com/statamic/docs/issues/1819
* Updated the docs for the `Select` component so it more closely mirrors the `Combobox` docs
* General tidy up of the component (sorry for the large diff! 😬)
* Various accessibility improvements
* A handful of minor UI fixes

### CODE REVIEW

File: resources/js/components/fieldtypes/TagsFieldtype.vue [hunk 1]
```diff
@@ -8,6 +8,7 @@
         :placeholder="__(config.placeholder)"
         :read-only="isReadOnly"
         :taggable="true"
+        :should-open-dropdown="({ open }) => open && options.length > 0"
```
Comment (jasonvarga) [inline resources/js/components/fieldtypes/TagsFieldtype.vue]: **Bug:** `shouldOpenDropdown` is called with a plain boolean (`props.shouldOpenDropdown(open)` in Combobox.vue:282), but this destructures `{ open }` from that boolean — which yields `undefined`. The function will always return falsy, preventing the dropdown from ever opening or closing for the Tags fieldtype.

Either:
- Change the call site to pass an object: `props.shouldOpenDropdown({ open })`
- Or change this to: `(open) => open && options.length > 0`

Since the default `() => true` ignores the argument, passing an object would be the safer API choice for future consumers.

File: resources/js/components/ui/Combobox/Combobox.vue [hunk 2]
```diff
@@ -222,307 +250,288 @@ const filteredOptions = computed(() => {
...
                             <ComboboxInput
-                                v-if="searchable && (dropdownOpen || !modelValue || (multiple && placeholder))"
+                                v-if="shouldShowInput"
+                                :id
+                                :placeholder
                                 ref="search"
-                                class="w-full bg-transparent text-gray-900 dark:text-gray-300 opacity-100 focus:outline-none placeholder-gray-500 dark:placeholder-gray-400 [&::-webkit-search-cancel-button]:hidden"
+                                class="w-full bg-transparent text-gray-900 dark:text-gray-300 opacity-100 focus:outline-none placeholder-gray-500 dark:placeholder-gray-400 [&::-webkit-search-cancel-button]:hidden cursor-pointer"
+                                :class="{
+									'placeholder-gray-900! dark:placeholder-text-gray-300!': selectedOption && !multiple && !dropdownOpen
```
Comment (jasonvarga) [inline resources/js/components/ui/Combobox/Combobox.vue]: Tailwind class typo: the dark mode class is `placeholder-text-gray-300!` but the light mode version is `placeholder-gray-900!` (no `text-` prefix). Should be `placeholder-gray-300!` to match.

File: resources/js/components/ui/Combobox/Combobox.vue [hunk 3]
```diff
@@ -222,307 +250,288 @@ const filteredOptions = computed(() => {
...
 
 function onPaste(e) {
-    if (!props.taggable) {
-        return;
-    }
+	if (!props.taggable) return;
 
     const pastedValue = e.clipboardData.getData('text');
 
     updateModelValue([...props.modelValue, ...pastedValue.split(',').map((v) => v.trim())]);
```
Comment (jasonvarga) [inline resources/js/components/ui/Combobox/Combobox.vue]: `modelValue` defaults to `null`. Spreading `null` throws a `TypeError`. Compare with `pushTaggableOption` (line 330) which correctly uses `props.modelValue ?? []`.

```suggestion
    updateModelValue([...(props.modelValue ?? []), ...pastedValue.split(',').map((v) => v.trim())]);
```

File: resources/js/components/ui/Combobox/Combobox.vue [hunk 4]
```diff
@@ -547,18 +556,18 @@ defineExpose({
                                 v-if="!disabled && !readOnly"
                                 type="button"
                                 class="opacity-75 hover:opacity-100 cursor-pointer"
-                                :aria-label="__('Deselect option')"
+                                :aria-label="__('Remove :label', { label: getOptionLabel(option) })"
```
Comment (jasonvarga) [inline resources/js/components/ui/Combobox/Combobox.vue:548]: This PR introduces several new user-facing strings (`'Remove :label'`, `'Clear selection'`, `':count of :max selections'`) that don't appear in any `lang/*.json` files. The old `"Deselect option"` string (translated in 20+ lang files) is now orphaned.

File: resources/js/components/ui/Combobox/Combobox.vue [hunk 5]
```diff
@@ -222,307 +250,288 @@ const filteredOptions = computed(() => {
...
-watch(filteredOptions, () => {
-	nextTick(() => scrollbarRef.value?.update());
-});
-
 function clear() {
     searchQuery.value = '';
     emit('update:modelValue', null);
 }
 
+function select(option) {
```
Comment (jasonvarga) [inline resources/js/components/ui/Combobox/Combobox.vue]: Nit: `option` parameter is declared but never used.
```suggestion
function select() {
```

File: resources/js/components/ui/Combobox/Combobox.vue [hunk 6]
```diff
@@ -222,307 +250,288 @@ const filteredOptions = computed(() => {
...
-										'min-h-[5rem]': filteredOptions.length === 2,
-										'min-h-[7.5rem]': filteredOptions.length >= 3,
-                                        'pr-3': scrollbarRef?.isVisible,
-                                    }"
-                                    data-ui-combobox-viewport
-                                >
-                                    <ComboboxEmpty class="p-2 text-sm" data-ui-combobox-empty>
+                            <div ref="viewport" class="relative max-h-[300px] overflow-y-auto py-2" data-ui-combobox-viewport>
+                                <!-- Hidden width measurer for wide dropdown mode -->
+                                <div v-if="adaptiveWidth" aria-hidden="true" class="h-0 overflow-y-clip px-2">
```
Comment (jasonvarga) [inline resources/js/components/ui/Combobox/Combobox.vue:465]: Nit: when `adaptiveWidth` is true this renders every filtered option in a hidden div, which bypasses the virtualization below. Fine for small lists, but might be worth documenting that `adaptiveWidth` isn't recommended for large datasets.

**Review by jasonvarga — DISMISSED** [review]
> This review was generated by Claude.

Nice overhaul — the removal of the custom Scrollbar, fixed max-height dropdown, and accessibility improvements are all great. A few issues need addressing before merge, the most critical being a bug that would break the Tags fieldtype entirely.

File: resources/js/components/ui/Combobox/Combobox.vue (hunk 4 above)
Comment (jasonvarga) [reply resources/js/components/ui/Combobox/Combobox.vue:548]: Ignore this one.

**Review by jasonvarga — COMMENTED** [review]
.
