### PR TITLE
REST API

### LINKED ISSUE #1116: 404s through the API should give JSON responses
When using the API to point to an entry, and it doesn't exist, it should respond with JSON instead of the 404 view.

In our `RouteServiceProvider`, we're manually aborting with 404s when stuff isn't found.

Probably better to throw some kind of `ItemNotFoundException` where we can adjust the response better.

### PR DESCRIPTION
**Pull request by jesseleite**
Closes #1116, #1118, #1119, #1120, #1121, #1122, #1123, #1124.

### CODE REVIEW

File: src/helpers.php [hunk 1]
```diff
@@ -18,6 +18,22 @@ function cp_route($route, $params = [])
     return $route;
 }
 
+function api_route($route, $params = [])
```
Comment (jasonvarga) [inline src/helpers.php]: Can we call this `statamic_api_route` or `Statamic\Statamic::apiRoute()`?

Feels generic enough that it could conflict with someone's app pretty easily.

Comment (jesseleite) [reply src/helpers.php]: Or trait?  Or do you think the helper is something other people will use?

Comment (jasonvarga) [reply src/helpers.php]: I think putting it in `Statamic` is enough. We have `isApiRoute` in there, it's pretty similar.
