### PR TITLE
✨ Brand New Antlers Engine ✨

### LINKED ISSUE #1798: Can't render Antlers in content
## Bug Description

I have the following in a nav structure:
```yaml
    title: '&copy; {{ misc:organization_name }}. All Rights Reserved.'
```

In my template I have this:
```html
{{ title }}
```

Which outputs: 
image
If I do this instead: `{{ title }}{{ misc:organization_name }}`, I get:
image

## How to Reproduce

1. Create a global with some data.
2. Create a Nav item whose title references the above global
3. In a template, reference the nav and that item's `title`

## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #1945: {{ if {collection:count in="collection_name" taxonomy:year="2019"} > 0}} throws an error when taxonomy condition is added
## Bug Description
When a taxonomy condition is added to collection:count based "if" statment i.e.: {{ if {collection:count in="collection_name" taxonomy:year="2019"} > 0}} an error is thrown:
image
image

It happens both if filtered collection has entries or not.

## How to Reproduce
Try to check it there are entries in collection with count and taxonomy filter added.
image

## Extra Detail
When taxonomy filter is removed - everything works fine.
image

## Environment
MacOs 10.4.16, Valet, PHP 7.3.18

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.3.18

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #2001: {{ if (collection == "pages") && (parent:slug != "home")  }} causes error
## Bug Description
{{ if (collection == "pages") && (parent:slug != "home")  }} causes error.

## How to Reproduce
{{ if collection == "pages" && parent:slug != "home" }}
{{ if collection == "pages" && page:slug != "home" }}
{{ if collection == "pages" AND parent:slug != "home" }}
{{ if (collection == "pages") && (parent:slug != "home") }}

All versions causes an error.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #2066: {{ select_var:label }} is not working
To get the labels of the select field you do {{ select_var:label }}. This is not outputting anything. I can get the default of value working with {{ select_var }}.

Make a select with key and label options. Try to use in template like email or on a form submission tag with {{ select_var }}, it works, now try and do with {{ select_var:label }}, it outputs nothing.

Side note: I tried this as well: {{ select_var }}{{ label }}{{ /select_var }}

On docs there is a typo too. https://statamic.dev/fieldtypes/select#templating
```
<p id="{{ select }}"> Oh yeah? {{ select:value }}</p> <<< This is the same thing...I think you want this:
<p id="{{ select }}"> Oh yeah? {{ select:label }}</p>
```

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #2161: Noparse issue with markdown fields
## Bug Description

I have a markdown field with the following contents:

```
{{ color.label }}
```

This is what gets output when I dump the field in my templates:

```
<p>noparse_56c56f2a2936bb9da06452fbd043aec8</p>
```

The final html however is just

```
<p></p>
```

Seems like the `{{ color.label }}` is somehow being parsed.

## Environment

**Statamic version:** 3.0.0.-beta-41

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #2505: Modifier doesn't accept parameter
## Bug Description
I'm trying to pass `{{ site:short_locale }}` as a parameter to a custom modifier. Is this even supposed to work?

The modifier `$params` in this example is `null`:
```html
{{ title :translate="site:short_locale" }}
```

The modifier `$params` in this example is `{site:short_locale}`:
```html
{{ title translate="{site:short_locale}" }}
```

## How to Reproduce
Create a modifier and try to pass the parameter like in the example above.

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9
aerni/translator dev-feature/statamic-v3

### LINKED ISSUE #2655: modifier & logical operators in conditions
## Bug Description & How to Reproduce
The condition ...
```
{{ if {index|mod:4} == 0 or {index|mod:4} == 3 }}
```
... is always true, even if the index is 1 or 2, should only be true with index 0, 3, 4, 7 and so on. The modifier works as expected, if i output it directly. I tested this on the latest version.

## Extra Detail
https://statamic.com/forum/4900-antlers-modifier-logical-operators-in-combination

## Environment
**Statamic version:** 3.0.14
**PHP version:** 7.4
**Install method (choose one):** Fresh install from `statamic/statamic`

### LINKED ISSUE #2671: Passing data through a partial to a grandchild partial results in "NULL"
## Bug Description
I'm attempting to pass data from the CMS via a `{{ collection }}` loop through a child `partial` to the origin's grandchild `partial`. This is because I have a base `card` partial that I've extended with modified card partials like `_card_featured` 

I think this is a bug based on my testing. I've tried a bunch of different solutions including different syntax, `raw` modifier and scoping the passed data. 

### Example: 
Parent HTML:
```{{ collection:blog_posts }}
    {{ partial:blog_posts/card_featured
        :p_background_color="background_color"
        :p_title="card:title"
    }}
    {{ /collection:blog_posts }}

```

`blog_posts/card_featured` partial: 
``` 
{{ partial:components/card classes="bg-gradient-to-br from-{p_background_color} to-{p_background_color}-900
text-white" }}
<div class="p-4">
    <h3>{{ title }}</h3>
</div>
{{ /partial:components/card }}
```

`_card.antlers.html` (base card):
```
<a href="#" class="flex flex-col rounded-sm shadow group {{ classes }}">
    {{ slot }}
</a>

```

## How to Reproduce
I have replicated the issue in a new clean Statamic V3 repo and stripped out all unnecessary things. 
1. Clone this repo: https://github.com/austriker27/statamic-partial-grandchild
2. Inspect the centered `<a>` tag on the page and you will see the gradient classes have `NULL` in them. However when you ` {{ dump }}` you will see the data is correct there. 
Rendered HTML:
```
<a href="#" class="flex flex-col rounded-sm shadow group bg-gradient-to-br from-NULL to-NULL-900
text-white">
    <div class="p-4">
    <h3>Yada, yada, yada...</h3>
</div>
</a>
```

## Extra Detail

[YAML file with the `background_color` data](https://github.com/austriker27/statamic-partial-grandchild/blob/master/content/collections/blog_posts/yada-yada-yada.md) 

## Environment

Statamic 3.0.19 Solo
Laravel 8.10.0
PHP 7.4.8
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

Thanks gents! Statamic is the best thing ever and I appreciate you.

### LINKED ISSUE #2722: Some Antlers logic not working combining modifiers
## Bug Description
I've got an antlers statements that I feel should work but doesn't. I ended up making a custom modifier.

`{{ if pin:event_date|is_today || pin:event_date|is_future }}`
`{{ if (pin:event_date|is_today) || (pin:event_date|is_future) }}`

`pin` is an `entries` field with `max_items: 1`.

## How to Reproduce

1. Give a blueprint a field called `event_date`.
2. Use the entries field to add events to a page for example.
3. Loop through the entries.
4. Use the above logic in your template.

## Extra Detail
Screenshot 2020-10-23 at 16 03 20

## Environment
Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.10
edalzell/mailchimp 2.1
jonassiewertsen/statamic-livewire 2.1.1

### LINKED ISSUE #3097: Collection tag flawed. Maybe deeper Antlers/Syntax issues?
## Bug Description
Very weird things happen with my collection tag.

```
{{ collection from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="random"
}}
```

When I change it to:
```
{{ collection from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="{{ randomizer ? 'random' : 'order' }}"
}}
```
I get
```
Facade\Ignition\Exceptions\ViewExceptionWithSolution
Modifier [from] not found
The from modifier was not found.
```

For more weirder things: When I change it to (linebreak before 'from='):
```
{{ collection
  from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="{{ more ? 'random' : 'order' }}"
}}
```

I get my entries, but they are from a completely different collection. Seems something really flawed with Antlers?

## Environment
Statamic 3.0.38 Solo
Laravel 8.21.0
PHP 7.4.10

### LINKED ISSUE #3286: Yield and section tags are affected by order
## Bug Description

The order in which yield and section tags are used can affect the result.

For example, if the yield tag is parsed before the corresponding section tag, it won't work.

## How to Reproduce

Use a yield tag before a section tag. The example provided to us was a dark mode toggle with accompanying js that needed to go in the head.

```
// layout

<html>
<head>
  {{ yield:dark_mode }}
</head>
<body>
  <nav>
    ...
    {{ partial:dark_mode_toggle }}
  </nav>
  {{ template_content }}
</body>
```

```
// dark_mode_toggle

<button>toggle</button>
{{ section:dark_mode }}
<script>some js</script>
{{ /section:dark_mode }}
```

If the `section` tag was used inside the _template_ it would work, because the template (and therefore the section tag) would be parsed before the layout. 

## Extra Detail

A solution might be to change how the yield tag works.
Maybe it could output a placeholder string rather than performing the replacement right there.
Then, after the whole view (template+layout) has been rendered, it could replace all the yields.

## Environment

**Statamic version:** 3.0.44

### LINKED ISSUE #3381: Antlers if-statements do not evaluate tags correctly when using more than one
## Bug Description
We're super happy users Statamic, but have experienced some weird behavior when working with if conditions in certain situations. We believe it occurs when having more than one "tag" in an if-statement. The tag isn't evaluated to the correct value when using more than one tag in the same if-statement. 

I tried to boil it down to a few minimal examples and also did a bit of digging in the source to see the actual PHP output, it seems very likely that it's a bug, or at least some undocumented odd magic that only works in certain situations.

## How to Reproduce
See examples below. Seems to happen when you use more than one tag in the same if-statement.

### Example 1
The following:
```
{{ if collection:handle === "news" || collection:handle === "services" }}
```
Parsed as correctly as "services" in the first expression, but not the second:
```php
<?php if ('services' === "news" || null === "services"): ?>
```

### Example 2
The following does however work for one expression, but not two:
```
{{ if collection:handle === "news" }}
```
Parsed correctly as "services"
```php
<?php if ('services' === "news"): ?>
```

### Example 3
This doesn't work at all, although this is what I'd expect to work after reading the documentation on ["Using tags in conditions"](https://statamic.dev/antlers#using-tags-in-conditions)
```
{{ if {collection:handle} === "news" }}
```
Parsed as NULL:
```php
<?php if (NULL === "news"): ?>
```

### Example 4
Similarly, using two expressions doesn't work:
```
{{ if {collection:handle} === "news" || {collection:handle} === "services" }}
```
Parsed as NULL in both places:
```php
<?php if (NULL === "news" || NULL === "services"): ?>
```

## Environment
Statamic 3.0.46 Pro
Laravel 6.20.16
PHP 7.4.15
statamic/ssg dev-master
withcandour/aardvark-seo 2.0.9

Starter kit

### LINKED ISSUE #3514: Can't use `old` variable with dynamic key
## Bug Description

I've got a site where we loop over form fields. When looping through, we need to be able to access `old` variables by their keys. However, we don't seem to be able to use a 'dynamic' key (where we get the field `handle` for example).

Here's a list of Antlers syntax I've tried:

* `{{ old[handle] }}`
* `{{ old:[handle] }}`
* `{{ old{handle} }}`
* `{{ old:{handle} }}`

## How to Reproduce

* Create a form with fields with required fields
* Add form to template & loop through the fields
* When looping through, try to do `value="{{ old:{handle} }}"` on one of the form inputs. 
* Submit the form (and know there's gonna be validation errors).
* Once page has reloaded, the output won't be as expected (the old value)

For the record, this is something that was broken on v3.0 as well, I just never got round to reporting it then.

## Extra Detail

I can't quite remember which ones which but one of them returned the actual Antlers code `{{ old:{handle} }}` for example, whereas the other just returned an empty string. I imagine this is a parser/regex issue.

## Workaround

I've developed a workaround tag for the meantime until this is properly fixed, in case it's useful for anyone else.

```php
<?php

namespace App\Tags;

use Statamic\Tags\Tags;

class OldValueTag extends Tags
{
    protected static $handle = 'old_value';

    // {{ old_value :key="handle" }}

    // this tag is used to get old values of fields. Statamic's {{ old }}
    // doesnt work if you need to pass in a handle from a form. Hence the need
    // for this custom tag

    public function index()
    {
        return old($this->params->get('key'));
    }
}
```

## Environment

```
Statamic 3.1.6 Solo
Laravel 8.36.2
PHP 8.0.3
doublethreedigital/duplicator 1.3.0
```

### LINKED ISSUE #3610: Using double quoted parameters for modifiers in Antlers if condition throws error about unexpected double-quote
## Bug Description
Using double quoted parameter for modifiers in Antlers if condition throws error about unexpected double-quote. This goes against what is written in the documentation on this page: https://statamic.dev/modifiers/contains#arrays

It shows the following example there:
```
{{ if (foods | contains:"vegan bacon strips") }}
```
## How to Reproduce
```
{{ if (current_uri | contains:"project") }} asdfasdf {{ /if }}
```
Throws the following error:
```
Statamic\View\Antlers\SyntaxError
syntax error, unexpected double-quote mark
```
## Extra Detail
I need to use parameter in such way so that I can include special characters e.g. `/project/`. Parameter like  `/project` works fine, but `/project/` does not and produces another, different syntax error most likely due to the parameter ending with a slash.
## Environment

Statamic 3.1.10 Solo
Laravel 8.25.0
PHP 7.4.13
octoper/statamic-inline-assets 4.0.3
statamic/ssg 0.4.0

### LINKED ISSUE #3624: multi condition in if statement does not work
## Bug Description
`{{ if view:image|length > 5 && view:image|length < 9 }}` is true when array variable has 10 items
## How to Reproduce
```
---
image:
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
    - https://placeimg.com/412/280/people/sepia
---
{{ if view:image|length > 5 && view:image|length < 9 }} // true --> should be false
{{ if view:image|length > 5 && 8 < 9 }} // true
{{ if 8 < 9 && view:image|length > 5 }} // true
```
## Extra Detail

update: ` {{ if view:image|count > 5 && view:image|length < 9 }}` // false
## Environment
Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.3.12
doublethreedigital/duplicator 1.3.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #3631: Antlers tag is rendered in bard code block
I was writing something about SEO Pro on my blog and I noticed the `{{seo_pro:meta}}` tag gets rendered on the page when I have it in a code block in bard content. Other antlers tags are not being rendered, as expected.

Also a preceding @ doesn't work. Example bard content in a code block:

```
{{# base.antlers.html #}}

{{ if environment != 'local' }}
  {{ seo_pro:meta }} <-- gets rendered
{{ /if }}
```

Expected behaviour would be to not render any tag when its in a code block. Is there any way to prevent this from happening?

Thanks, Nick

### LINKED ISSUE #3636: `where` doesn't work on terms
## Bug Description

You can't use the `where` modifier on a list of terms, in an entry.

## How to Reproduce

1. Create a taxonomy, `tags` and have a `foo` text field on it
2. Add 3 terms, 2 of which have `bar` in the `foo` field
3. Add that taxonomy to a collection
4. Create an entry and add those 2 terms to it
5. In the entry template have:
```
{{ tags where="foo:bar" }}
    {{ title }}
{{ /tags}}
```

I'd expect to see those two terms, but nothing is shown.

## Extra Detail

Entry:
```
---
title: 'Some tags'
tags:
  - blue
  - green
```

Term:
```
title: Blue
order: 2
updated_by: e8982d24-f8f9-4e2f-9286-062f9d98aa4a
updated_at: 1620098429
foo: bar
```

Blueprint:
```
title: Posts
template: post
layout: layout
mount: 65d2c20e-e54a-4b0a-866c-d8176e5dd2f3
taxonomies:
  - tags
```

## Environment

Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 8.0.5
No addons installed

### LINKED ISSUE #3685: simple OR/AND condition does not work
## Bug Description
There is a real need of checking more than one variable in conditions. 
example: when we use multisite, and we check entry id, we have to check localized and origin id.

## How to Reproduce
```
category:
  - 4734e652-c9f7-435d-aaf6-3c40abb7f040
  - 50fc0090-fa52-4d61-9365-040e5fae5a39
```

`{{ category | raw | dump }}`  
image

```
{{ category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 | dump }}
{{ category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 | dump }}
{{ category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 | dump }}
{{ category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 | dump }}
```
image
```
{{ if category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

```
{{ if category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

```
{{ if category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

## Extra Detail

```
{{ if category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}
    <br>
    <div>category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040</div>
    {{ if category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}
    <br>
    <div>category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040</div>
    {{ if category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}

```
dump is:
image

(looks like) same (old) issues: [ #2655](https://github.com/statamic/cms/issues/2655), [#3624](https://github.com/statamic/cms/issues/3624)
## Environment

Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.3.12
doublethreedigital/duplicator 1.3.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #3790: Can't access view's array variable with dynamic key
## Bug Description
When creating an array variable into a given view, trying to access the keys with a dynamic value doesn't seem to work. (Antlers)

## How to Reproduce
1. Create a collection in the CP. E.g. 
```
menu_items: 
  item_1: 
    icon_id: locate
  item_2: 
    icon_id: phone
  item_3: 
    icon_id: basket
  item_4: 
    icon_id: profile
```

2. Create an Antlers view with a template variable at the top. E.g. 
```
---
viewbox:
   locate: some_data
   phone: some_data
   basket: some_data
   profile: some_data
---
```

3. Loop over the collection (e.g. `menu_items`) and try to get template's variable keys dynamically
```
{{ menu_items }}
  {{ icon_id }} // --> locate, phone, basket, profile
  {{ view:viewbox[icon_id] }} // no output
{{ /menu_items }}
```

## Environment
**Statamic version:** 3.1.18
**PHP version:** 8.0.2
**Laravel version:** 8.43.0

**Install method (choose one):**
- Starter kit (`statamic/statamic`)

### LINKED ISSUE #3835: Using `??` instead of `or` causes form tag parser weirdness
## Bug Description

If you use `??` instead of `or` inside a `form:create` tag, the `errors` are incorrect.

It might not have anything to do with the `form:create` tag at all, but that's just where we noticed it.

Ref #3669 

## How to Reproduce

1. Create a form named `contact`
2. Add a required field to the blueprint, just so there's an easy way to cause a validation error.
3. Use this template to output the form:
   ```
   {{ form:create in="{foo ?? 'contact'}" }}
     {{ errors | dump }}
     {{ errors | ul }}
     <button>submit</button>
   {{ /form:create }}
   ```
4. See that `errors` is a `ViewErrorBag`, and that it's not output as a list.
5. Change `??` to `or`
6. See that `errors` is an array, and they're output correctly.

## Environment

**Statamic version:** 3.1.22

### LINKED ISSUE #3980: Shorthand if/else doesn't work with pagination
## Bug Description

Using the shorthand `if/else` statement does not work when used with pagination, however the basic `if/else` does.

## How to Reproduce

This doesn't work:
```
{{ collection:work limit="8" paginate="true" as="posts" sort="date:desc" }}

    {{ posts }}
        <p>{{ short_title ? short_title : title }}</p>
    {{ /posts }}

    {{ paginate }}
    ...
    {{ /paginate }}

{{ /collection:work }}
```
However, this does:
```
{{ collection:work limit="8" paginate="true" as="posts" sort="date:desc" }}

    {{ posts }}
        <p>{{ if short_title }} {{ short_title }} {{ else }} {{ title }} {{ /if }}</p>
    {{ /posts }}

    {{ paginate }}
    ...
    {{ /paginate }}

{{ /collection:work }}
```
## Environment

**Statamic version:** 3.1.27

**PHP version:** 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #4066: in_array or contains not working as expected
Hi Guys, 

I'm having trouble checking to see if a value is in an array. I have a collection called websites, and it has an array of software which is an entries field pointing to another collection called software. I'm running the code below on the show page for the specific software entry

```
{{ collection:websites }}
            {{ software }}
                {{ if id == page:id }} 
                    <p>manual: {{ id }}</p>
                {{ /if }}
            {{ /software }}

            {{ if software | contains:{page:id} }}
                <p>in_array: {{ id }}</p>
            {{ /if }}
{{ /collection:websites }}
```

The manual loop running through the software loop correctly matches ids, but the contains loop doesn't. I get the same result using in_array.

The software entry id looks like this in its .md file
```
id: 61dec82d-101f-4417-a208-ad5d0d7dc34d
```

and the website entry looks like this
```
software:
  - 61dec82d-101f-4417-a208-ad5d0d7dc34d
```

Even if I manually add the id as a string to the `contains` variable it still doesn't recognise it

### LINKED ISSUE #4099: Logical operator '||' seen as modifier in some cases
## Bug Description
The logical operator `|| `is seen as `|'modifier' ` not as an 'or' though only in some cases.
In this case` {{if is_small_article || collection:handle == 'vacancies'}} `  and error was returned. `Modifier [] not found`
But for two variables `{{if feature_text || feature_quote}}`  it works without issue.

## Environment

**Statamic version:** 3.1.32

**PHP version:** 8.0

### LINKED ISSUE #4249: ensure_right doesn't work with `|`
## Bug Description
I'm working on SEO titles for my website, the common convention is to use `title | site name`. I'm overriding some of my pages and want to fall back to `site name` when I break something... I want to avoid `| site name` in the title.

I thought I'd use ensure_right to get around this:

```
<title>{{ title ensure_right=" |" }} {{ config:app:name }}</title>
```

However, I found this doesn't work. I assume `|` is reserved for use in conditional statements or the parser is getting confused about it. Although I found that `&` works fine.

With different characters it works as expected:

```
<title>{{ title ensure_right=" @" }} {{ config:app:name }}</title>
<title>{{ title ensure_right=" ," }} {{ config:app:name }}</title>
<title>{{ title ensure_right=" ," }} {{ config:app:name }}</title>
<title>{{ title ensure_right=" &" }} {{ config:app:name }}</title>
<title>{{ title ensure_right=" !" }} {{ config:app:name }}</title>
```

It seems like most other options work fine except `|`.

## Environment
Statamic 3.2.1 Pro
Laravel 8.56.0
PHP 8.0.6
statamic/ssg 0.8.0

### LINKED ISSUE #5128: starts_with doesn't accept £ param strings
### Bug description

I'm trying to set some CSS classes on a box if the contained string starts with a Pound sign.
However, I'm seeing an error when trying to do so:

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected token ":" on line 5 of: <td class=" px-1 py-3 border-b-2 border-gray-200 text-center align-middle <?php if (true:£): ?> font-semibold text-water-500 <?php endif; ?> " >
```

### How to reproduce

1. Store a text field starting with an “£”.
2. Try to call the `starts_with` modifier.

```html
<td class="
        px-1 py-3
        border-b-2 border-gray-200
        text-center align-middle
        {{ if text|starts_with:£ }}
            font-semibold text-water-500
        {{ /if }}
    "
>
```

Using this block, however, works just fine – using an “A”:
```html
        {{ if text|starts_with:A }}
            font-semibold text-water-500
        {{ /if }}
```

### Logs

```shell
[previous exception] [object] (Statamic\\View\\Antlers\\SyntaxError(code: 0): syntax error, unexpected token \":\" on line 5 of:

<td class=\"
        px-1 py-3
        border-b-2 border-gray-200
        text-center align-middle
        <?php if (true:£): ?>
            font-semibold text-water-500
        <?php endif; ?>
    \"
>
    <?php if ('YES' === 'YES'): ?>
        {{ svg:checkmark class=\"text-green-500 inline-block w-6 h-6\" }}

    <?php elseif ('YES' === 'NO'): ?>
        {{ svg:crossmark class=\"text-green-500 inline-block w-6 h-6\" }}

    <?php else: ?>
        {{ text }}
    <?php endif; ?>
</td>
 at /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php:1342)
[stacktrace]
#0 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(716): Statamic\\View\\Antlers\\Parser->parsePhp('<td class=\"\
   ...')
#1 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(172): Statamic\\View\\Antlers\\Parser->parseConditionPairs('<td class=\"\
   ...', Array)
#2 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<td class=\"\
   ...', Array)
#3 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<td class=\"\
   ...', Array)
#4 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#5 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#8 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('page.item.featu...')
#9 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('page.item.featu...')
#10 [internal function]: Statamic\\Tags\\Tags->__call('page.item.featu...', Array)
#11 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#12 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#13 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#14 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(341): Statamic\\View\\Antlers\\Parser->parseCallbackTags('            <tr...', Array)
#15 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(288): Statamic\\View\\Antlers\\Parser->parseLoopInstance('            <tr...', Array)
#16 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}(Array, 0)
#17 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(677): array_map(Object(Closure), Array, Array)
#18 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(289): Illuminate\\Support\\Collection->map(Object(Closure))
#19 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(223): Statamic\\View\\Antlers\\Parser->parseLoopVariables('<table class=\"w...', Array)
#20 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(175): Statamic\\View\\Antlers\\Parser->parseVariables('<table class=\"w...', Array)
#21 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<table class=\"w...', Array)
#22 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<table class=\"w...', Array)
#23 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#24 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#25 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#26 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#27 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('page.item.featu...')
#28 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('page.item.featu...')
#29 [internal function]: Statamic\\Tags\\Tags->__call('page.item.featu...', Array)
#30 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#31 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#32 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#33 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<!-- Hero stage...', Array)
#34 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<!-- Hero stage...', Array)
#35 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<!-- Hero stage...', Array)
#36 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#37 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#38 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#39 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/View.php(94): Illuminate\\View\\View->render()
#40 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Responses/DataResponse.php(154): Statamic\\View\\View->render()
#41 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Responses/DataResponse.php(45): Statamic\\Http\\Responses\\DataResponse->contents()
#42 /Users/jm/Web/some-project/vendor/statamic/cms/src/Structures/Page.php(382): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#43 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#44 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#45 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#46 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/jm/Web/some-project/vendor/withcandour/aardvark-seo/src/Http/Middleware/RedirectsMiddleware.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): WithCandour\\AardvarkSeo\\Http\\Middleware\\RedirectsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/jm/Web/some-project/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#65 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#73 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#74 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#75 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#76 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/jm/Web/some-project/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/jm/Web/some-project/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/jm/Web/some-project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#103 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#104 /Users/jm/Web/some-project/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#105 /Users/jm/.composer/vendor/laravel/valet/server.php(234): require('/Users/jm/Web/s...')
#106 {main}
"}
```

### Versions

Statamic 3.2.31 Pro
Laravel 8.76.2
PHP 8.1.2
doublethreedigital/duplicator 2.1.0
rias/statamic-color-swatches 2.0.5
withcandour/aardvark-seo 2.0.21

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by JohnathonKoster**
This PR provides a complete rewrite of the Antlers parser to separate it into two pieces:

* An Antlers parser: parses input strings into a list of nodes that can be evaluated to produce a final string
* An Antlers Runtime: a virtual execution environment to evaluate parser nodes

**Important Note**: While some new Antlers features look like PHP, Antlers is still not PHP :)

## Issues Accounted For

This PR resolves, or makes improvements for, the following issues:

* Closes #4249 - ensure_right doesn't work with `|`

Developers may use shorthand syntax to supply the vertical pipe as an argument: `{{ title | ensure_right:"|" }}`

Developers utilizing parameter-style modifiers will still need to use the HTML entity version: `{{ title ensure_right=" &vert;" }}`

* Closes #4099 - Logical operator `||` seen as modifier in some case
* Closes #3636 - `where` doesn't work on terms
* Closes #4066 - in_array or contains not working as expected
* Closes #2671 - Passing data through a partial to a grandchild partial results in "NULL"
* Closes #2066 - `{{ select_var:label }}` is not working
* Closes #1798 - Can't render Antlers in content
* Closes #3286 - Yield and section tags are affected by order
* Closes #2505 - Modifier doesn't accept parameter

Any tag/expression can be returned from an Antlers sub-expression. The `{{ title translate="{site:short_locale}" }}` syntax will work, but the variable reference will not.

* Closes #3624
* Closes #5128
* Closes #3980 - Shorthand if/else doesn't work with pagination
* Closes #3631 - Antlers tag is rendered in bard code block
* Closes #2161 - Noparse issue with markdown fields
* Closes #2655 - modifier & logical operators in conditions
* Closes #2722 - Some Antlers logic not working combining modifiers
* Closes #1945 - `{{ if {collection:count in="collection_name" taxonomy:year="2019"} > 0}}` throws an error when taxonomy condition is added
* Closes #3381 - Antlers if-statements do not evaluate tags correctly when using more than one
* Closes #3610 - Using double quoted parameters for modifiers in Antlers if condition throws error about unexpected double-quote
* Closes #2001 - `{{ if (collection == "pages") && (parent:slug != "home") }}` causes error
* Closes #3685 - simple OR/AND condition does not work
* Closes #3835 - Using `??` instead of `or` causes form tag parser weirdness

These two are now equivalent: `{ foo || 'contact' }` and `{ foo or 'contact' }`

* Closes #3790 - Can't access view's array variable with dynamic key
* Closes #3514 - Can't use `old` variable with dynamic key
* Closes #3097 - Collection tag flawed. Maybe deeper Antlers/Syntax issues?

For 3097, the syntax should preferentially use single-braces inside the tag, but double braces will *technically* work here:

```html
{{ collection from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="{ randomizer ? 'random' : 'order' }"
}}
```

Adds test coverage for #2529 (Can't use modifiers in array syntax). Cannot repro in current 3.2 branch, however.

Cannot reproduce #4993 with Runtime parser. Partial tag receives expected parameters.

## Ideas Implemented

* Fixes statamic/ideas#492 - Named slots for partials

Partial: `partials/_card.antlers.html`:

```html
<div class="max-w-sm rounded overflow-hidden shadow-lg">
    <img class="w-full" src="image/path.jpg" alt="{{ title }}">
    <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">{{ title }}</div>
        <p class="text-gray-700 text-base">{{ slot }}</p>
    </div>
    <div class="px-6 pt-4 pb-2">
        {{ if !slot:bottom }}
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#tag1</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#tag2</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#tag3</span>
        {{ else }}
            {{ slot:bottom }}
        {{ /if }}
    </div>
</div>
```

Other code:

```html
{{ partial:card }}

{{ slot:bottom }}
    <span>I'll appear in the bottom section.</span>
{{ /slot:bottom }}

Default slot content.
{{ /partial:card }}
```

* Fixes statamic/ideas#479 - `user:can` should be a conditional

Any Antlers tag/expression can now be used in a condition (even if has spaces, or HTML-like parameters):

```html
{{ if {user:cant do="edit projects collection"} }}

{{ else }}

{{ /if }}
```

* Fixes statamic/ideas#364 - Output array from custom tag as var rather than iterable tag pair
  * Results of tags (or any Antlers) can be assigned to variables if from an interpolation region:
    * `{{ articles = {collection:articles} }}`
    * `{{ data = {my_tag_pair_data} }}`
* Fixes statamic/ideas#200 - YAML front matter with Antlers 
  * Custom variables now takes its place
* Fixes statamic/ideas#41 - Temporary Variables in Antlers

## Backwards Compatibility

* All existing Antlers tests pass when targeting the updated runtime

There are some instances where backwards compatibility has been broken (Antlers tags nested inside other tags, and anything that is currently taking advantage of parser bugs).

Great care has been taken to break as little as possible, but accounting for every possible scenario in the wild is not possible. Because of this, existing Antlers has not been removed, and can be used on existing projects.

## Creating Variables

This PR allows developers to create variables within Antlers:

```html
{{ total = 0 }}

{{ loop from="1" to="10" }}
    {{ total += 1 }}
{{ /loop }}

<p>The total is: {{ total }}</p>
```

Sub-expression/interpolated regions can also be assigned to variables:

```html
{{ pages = {collection:pages limit="5"} }}

<p>Pages:</p>

{{# Use pages as if it were the actual tag #}}
{{ pages }}
    {{ if no_results }}

    {{ /if }}
{{ /pages }}
```

## Creating Arrays

Developers may create arrays within Antlers if they want to (although getting them from a view model, view composer, etc. is still preferred):

```html
{{ myarray = arr('one', 'two', 'three') }}
```

Associative arrays are also supported:

```html
{{
    my_array = arr(
                    "one" => 1,
                    "two" => 2,
                    "three" => arr(
                        1,
                        2,
                        3,
                        4 => arr(
                            1,
                            2
                        )
                    ))
}}
```

## Calling Methods

Developers may now call methods on objects using the `{{ VARNAME:METHOD_NAME() }}` syntax:

```html
{{ object:method() }}
```

Developers may also pass arguments to methods:

```html
{{ object:method('arg1', 'arg2', 'etc') }}
```

## Additional Improvements

* Can now use nested parenthesis to get as complex as you want
* Behavior of `{}` single brace sub-expressions (interpolations) as well as nested parenthesis is now deterministic
* Predictable/deterministic tag pairing algorithm
* Developers can now use self-closing Antlers tags: `{{ myarray | length /}}`
* Better parser error messages
* Internal runtime caching for augmentation (only persists for the current request)
* Large and extensive test suite
* Introduces a `once` tag-like to ensure that a part of a template only executes once
* Adds support for template stacks and queues
* Adds ways to tell the runtime how to resolve variable and tag name collisions
* Improves escaped content handling
* A low-level runtime "tracing" API that allows developers to create very complex integrations with third party tools
* Configurable block-list to prevent variable name patterns, tags, or modifiers from being executed
* And a _whole lot more_

## Upgrading/Downgrading

By default, all existing sites and all new sites will continue to use the regex Antlers parser.

To upgrade, set the `statamic.antlers.version` configuration option to `runtime`.

In `config/statamic/antlers.php`:

```php
<?php

return [


    'version' => 'runtime',

    // ...
];
```

To downgrade to "legacy" Antlers, set the value to `regex` (new default):

In `config/statamic/antlers.php`:

```php
<?php

return [


    'version' => 'regex',

    // ...
];
```

### CODE REVIEW

**Comment by jasonvarga** [comment]
Epic.

**Comment by robdekort** [comment]
Insane but _so_ welcome. ❤️

**Comment by jelleroorda** [comment]
You’re my personal hero 🦸‍♂️ , this is _epic_!

**Comment by FrittenKeeZ** [comment]
How will this affect performance?

**Comment by jasonvarga** [comment]
I personally haven't benchmarked it yet but apparently there's a huge improvement.

**Comment by JohnathonKoster** [comment]
> How will this affect performance?

For the vast majority of situations the parsing time is negligible now. As Jason mentioned, there will need to be benchmarks done :)

There are numerous things going on under the hood to help optimize performance:

1. Internal parser cache: remembers details about previously seen items (i.e., it is not uncommon to see `{{ url }}` and `{{ title }}` many times. The details of these are cached, and only the new positions are updated, for example). This technique is also utilized heavily in loops where the body of the loop is always only ever parsed once, and reused across all elements of the array.
2. Runtime augmentation cache: asking for repeated information on an object that required a `toAugmentedArray()` will have that initial call cached in a smart way (regardless of original tag pairs, etc.) - this alone has positive results for asset and entry heavy sites
3. Dynamic parser and analysis strategies (an example of this would be in the conditional pairing logic where it will shift its strategy depending on what it thinks the final result may look like [i.e., indexes are slower on small arrays, but are worth it on very complicated/large nested if statements])
4. Dynamic multi-byte support: analyzes upcoming input to see if `str_split` would be fine to use over `mb_str_split` (and related functions) for performance and memory improvements

Of course, the same advice holds as always to help improve performance:

1. Keep computationally expensive work out of Antlers: do complicated things in PHP, and use a view model, view composer, etc.
2. Deeply nested tag structures will still cause internal context switching, which will cause a lot of internal stack creation, and hurt performance over the long run

Hard numbers are difficult to throw around since it also depends on the execution environment, but on the limited number of complex sites that have been tested during development, a positive improvement has been seen. Undoubtedly there will be room for improvement :)

tl;dr: The compiled PHP from Blade will still win, but new Antlers gets very close to those speeds when sticking to the language features. The performance cost of actually getting your page's data and assets will be the bottleneck in the vast majority of cases.

**Comment by FrittenKeeZ** [comment]
That sounds very promising, as we have a quite entry and asset heavy site - I'm still in the process of migrating from v2, but any performance improvements are welcome :)

**Comment by ebeauchamps** [comment]
Wow. Just wow. Is this 4.0 time already?

**Comment by hmalaud** [comment]
Exciting 🤩  
Really.

**Comment by lokmanm** [comment]
This is so awesome, cant wait for this @JohnathonKoster 🙏

**Comment by freshface** [comment]
Nice, any ETA on the release?

**Comment by jasonvarga** [comment]
When it's ready. 😄

File: src/Providers/ViewServiceProvider.php [hunk 1]
```diff
@@ -25,14 +27,33 @@ public function register()
             return new Cascade($app['request'], Site::current());
         });
 
+        $antlersVersion = config('statamic.antlers.version', 'regex');
```
Comment (jasonvarga) [inline src/Providers/ViewServiceProvider.php:30]: I think since the intention is for this parser to eventually become the default, we should test it that way.

In `tests/TestCase.php` at the end of `resolveApplicationConfiguration` you can add this:

```
$app['config']->set('statamic.antlers.version', 'runtime');
```

(The other config bootstrapping we're doing in `getEnvironmentSetup` should really be in there too, but we'll fix that up separately)


When that's done and you run the tests, you'll see failures.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: src/Providers/ViewServiceProvider.php (hunk 1 above)
Comment (jasonvarga) [reply src/Providers/ViewServiceProvider.php:30]: I've added this to the PR myself. 👍

File: tests/Antlers/ScratchTest.php [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+namespace Tests\Antlers;
+
+use Facades\Tests\Factories\EntryFactory;
+use Statamic\Facades\Antlers;
+use Statamic\Facades\Collection;
+use Statamic\Structures\CollectionStructure;
+use Tests\PreventSavingStacheItemsToDisk;
+use Tests\TestCase;
+
+class ScratchTest extends TestCase
```
Comment (jasonvarga) [inline tests/Antlers/ScratchTest.php:10]: I've added this class as a temporary place to dump tests for issues I've noticed, without needing to think too hard about moving them to the right place. We can move the tests out to better places later.

File: tests/Antlers/ScratchTest.php [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+        EntryFactory::collection('test')->id('two')->slug('two')->data(['title' => 'Two'])->create();
+
+        // note: not specific to the collection tag
+        $template = '{{ title }} {{ collection:test }}{{ title }} {{ /collection:test }} {{ title }}';
+        $expected = 'Outside One Two  Outside';
+
+        $parsed = (string) Antlers::parse($template, ['title' => 'Outside']);
+
+        $this->assertEquals($expected, $parsed);
+    }
```
Comment (jasonvarga) [inline tests/Antlers/ScratchTest.php:27]: Notice that the `title` _after_ the loop takes the value of title in the last iteration of the loop.

It outputs `Outside One Two Two` but should be `Outside One Two Outside`.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

**Comment by jasonvarga** [comment]
I just want to preface my upcoming comments with... this whole thing is awesome and I (we) appreciate the insane amount of effort that went into it. Hopefully none of it comes across as complainy or ungrateful. There's just a lot to go through so I'm trying to keep it as brief as I can. 😄

**Comment by jasonvarga** [comment]
I added a couple of failing tests for some issues I found, too.

**Review by jasonvarga — DISMISSED** [review]

**Comment by RafaelKr** [comment]
@JohnathonKoster Did you commit this by accident? https://github.com/statamic/cms/pull/4257/commits/dc1c82885aef1b3fb8057212549042fb7a89508f#diff-b09259790486619ec08afbfe63ce7f7166f562506a823e66448175d77619835c

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster Did you commit this by accident? [dc1c828#diff-b09259790486619ec08afbfe63ce7f7166f562506a823e66448175d77619835c](https://github.com/statamic/cms/commit/dc1c82885aef1b3fb8057212549042fb7a89508f#diff-b09259790486619ec08afbfe63ce7f7166f562506a823e66448175d77619835c)

Sure did! Great catch! :)

File: src/Contracts/Antlers/ParserContract.php [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+     * This is so that multiple parses can store noparse
+     * extractions and all noparse can then be injected right
+     * before data is displayed.
+     *
+     * @param  string  $text  Text to inject into
+     * @return string
+     */
+    public function injectNoparse($text);
+
+    public function valueWithNoParse($text);
```
Comment (adevade) [inline src/Contracts/Antlers/ParserContract.php:56]: First function has lowercase **p**, and second one has uppercase **P**

**Comment by jackmcdade** [comment]
@JohnathonKoster Do you have a list of any new operators? For example, you show `{{ total += 1 }}` in one of your code snippets – what else is possible?

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster Do you have a list of any new operators? For example, you show `{{ total += 1 }}` in one of your code snippets – what else is possible?

This is the current table of possible assignment operators:

## Assignment Operators

| Name | Syntax | Description |
|---|---|---|
| Left Assignment Operator | `{{ var = anotherVar }}` | Sets the value of `var` to be equal to the value stored in `anotherVar`. |
| Addition Assignment Operator | `{{ var += anotherVar }}` | Adds `anotherValue` to the current value of `var`, and assigns the sum to `var`. |
| Subtraction Assignment Operator | `{{ var -= anotherVar }}` | Subtracts `anotherValue` from the current value of `var`, and assigns the difference to `var`. |
| Multiplication Assign Operator | `{{ var *= anotherVar }}` | Multiplies `anotherValue` by the current value of `var`, and assigns the product to `var`. |
| Division Assign Operator | `{{ var /= anotherVar }}` | Divides `var` by `anotherVar`, and assigns the quotient to `var`. |
| Modulus Assign Operator | `{{ var %= anotherVar }}` | Assigns the value of `var` mod `anotherVar` to `var`. |

**Comment by jackmcdade** [comment]
@JohnathonKoster Thank you! ❤️

**Comment by Pixney-William** [comment]
This is just amazing!

**Comment by jackmcdade** [comment]
WIP docs (7 day's worth of work so far) for anyone following along 😊 

https://statamic-new-antlers.netlify.app/new-antlers-parser

**Comment by theutz** [comment]
I hate to pollute a very important PR with blatant fanboy-ism...but...

### MY GOD THIS IS AMAZING

Thank you so much for all of this, @JohnathonKoster !

**Comment by michaelr0** [comment]
Awesome work!

Would it be much effort to make it compile to native PHP, like Blade does?

**Comment by JohnathonKoster** [comment]
> Awesome work!
> 
> Would it be much effort to make it compile to native PHP, like Blade does?

Not easily, no. It's possible, but I am not sure there would be many (immediately tangible) performance benefits in doing so with some of the magic things that Antlers lets you do with variables, augmentation, the way it manages iterations, recursion, etc.

Additionally, Antlers is also used for other things like route patterns, dynamic entry titles, is allowed in user content, etc. which would all need to be considered.

It's something I've thought a lot about, and would need to do some experimentation if that becomes the desired direction in the future.

Hope this helps!

**Comment by edalzell** [comment]
> 

why?

**Comment by edalzell** [comment]
> Would it be much effort to make it compile to native PHP, like Blade does?

Why @michaelr0?

**Comment by jackmcdade** [comment]
@michaelr0 here's a pretty good explanation of why Antlers is so powerful and important: https://statamic-3-dot-3.netlify.app/new-antlers-parser/#about. Many of things things wouldn't be possible with flat, compiled PHP.

**Comment by michaelr0** [comment]
@JohnathonKoster @edalzell @jackmcdade, Thanks for the explanation's, indeed it was in search of additional performance, but if it comes at the cost of a loss of flexibility for minimal gain and significant effort, then yes perhaps best not to worry about it.

**Comment by jasonvarga** [comment]
@JohnathonKoster Ignore the failure for now - I'm working on those still.

**Comment by jasonvarga** [comment]
Alright the tests are updated.

Now our old ParserTest and your new TemplateTest will both use the exact same tests, they are shared through a trait.

Now there are a handful of failures throughout the entire suite, and they're all for the same reason: #5238

The parser should be able to handle `QueryBuilder` instances, and automatically call `->get()` on them to convert them from a query to a collection of items.

There's a few new tests in `TemplateTest.php` that fail regarding query builders. If you can fix those, the other tests throughout the whole suite should resolve themselves.

**Comment by JohnathonKoster** [comment]
> hose, the other te

Sounds great! Thanks for getting the tests consolidated. I will take care of the failing items later this evening my time :)

**Comment by jasonvarga** [comment]
🥁 ...

**Comment by RafaelKr** [comment]
YES! 🚀 Been following this for a long time now. How will you celebrate this epic moment?  
Awesome work guys! Didn't test it yet, but I'm sure it was absolutely worth the effort!

**Comment by RafaelKr** [comment]
> @michaelr0 here's a pretty good explanation of why Antlers is so powerful and important: [statamic-3-dot-3.netlify.app/new-antlers-parser/#about](https://statamic-3-dot-3.netlify.app/new-antlers-parser/#about). Many of things things wouldn't be possible with flat, compiled PHP.

@jackmcdade the new docs state `A smarter, more forgiving matching engine so more things Just Work™"`.

Could someone elaborate what exactly this means? I'm a big fan of it myself, for example, when syntax-related things are more opinionated. So it doesn't matter whoever writes the Code in the end it will be very similiar - this leads to better readability and therefore better maintainability. This is one of the reasons the programming language Go was designed with very few keywords, so it's as simple as possible but of course still flexible enough to accomplish any task.

If "more things Just Work" means there are less bugs and discrepancies it's a good thing, of course!

**Comment by JohnathonKoster** [comment]
The easiest way I can think to explain the "more forgiving matching engine" is something like this:

```
{{ variable raw="here" }}

{{ /variable }}

{{ variable | upper }}
    {{ variable /}}
{{ /variable | upper }}
```

The updated engine would match those two pairs correctly, while the current engine may produce output similar to `{{ /variable | upper }}`.
