### PR TITLE
Fix deleting an entry with children from the tree view

### LINKED ISSUE #3791: Exception: "Root page cannot have children" in pages collection
## Bug Description
I believe it is related to multi-site setups

We have a site in development where we got the exception after the customer localized some sub-pages, they did not touch the home page.

In the tree files for the non-primary locales the `home` was missing and another page was the first in the tree. The `home` pages have already some translations in all languages.

What we had

``` yaml
tree:
  -
    entry: 84c597d7-52a9-4ab7-b06b-97fc492252b2
    children:
      -
        entry: b635d8ab-6a06-44ab-b3fe-67929f03b2a4
      -
        entry: e9788ce7-407d-409c-a7d2-10bd7cc07591
```

I just added the `entry: home` to fix it

``` yaml
tree:
  -
    entry: home
  -
    entry: 84c597d7-52a9-4ab7-b06b-97fc492252b2
    children:
      -
        entry: b635d8ab-6a06-44ab-b3fe-67929f03b2a4
      -
        entry: e9788ce7-407d-409c-a7d2-10bd7cc07591
```

## How to Reproduce

Starting from a fresh clone of statamic/statamic and after running following commands

```
composer update
cp .env.example .env
php artisan key:generate
```

1. Create a multi-site setup `php please multisite`
2. Add another page in the pages collection
3. Add sub-pages to this page
4. Localize and publish the page created in step 2
5. (Try to) Localize the page created in step 3 (It shows a loader but never ends)
6. Clear the cache

## Extra Detail
Might relate to #1666 

## Environment

Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 8.0.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### LINKED ISSUE #4453: Error when deleting page that has children
## Bug Description
When you delete a page that has children you get an error "Root page cannot have children". When you delete the children individually first you can bypass this bug.

## How to Reproduce
1. Add a page
2. Give the page one or more children
3. Delete that parent page

Or install Peak, it comes with pages featured in the example below.

`statamic new site studio1902/statamic-peak`

## Extra Detail
Possibly related to #3791
https://user-images.githubusercontent.com/69107412/136973617-43fb2fec-44e3-4460-8fdd-91e670470ceb.mov

## Environment
Statamic 3.2.14 Pro
Laravel 8.63.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit Peak

### PR DESCRIPTION
**Pull request by arthurperton**
This fixes #4453.

It may fix #3791 too, although I had trouble reproducing that one in the first place.

- The changes in `Tree->move()` fix 4453 
- The changes in `CollectionTreeController->update()` prevent any deleted pages from staying in the tree file afterwards (this issue was not reported)
- The changes in `Branch.vue` make sure that any orphaned children are moved up one level "in place", instead of moving them to the bottom of the list.

### CODE REVIEW

File: src/Structures/Tree.php [hunk 1]
```diff
@@ -293,7 +293,7 @@ public function move($entry, $target)
             return $this;
         }
 
-        if ($this->structure()->expectsRoot() && Arr::get($this->tree, '0.id') === $target) {
+        if ($this->structure()->expectsRoot() && Arr::get($this->tree, '0.'.$this->idKey()) === $target) {
```
Comment (jasonvarga) [inline src/Structures/Tree.php:296]: 🤣 the simplicity of this fix lol

File: resources/js/components/structures/Branch.vue [hunk 2]
```diff
@@ -134,13 +134,10 @@ export default {
...
-            let length = children.length;
-            for (let index = 0; index < length; index++) {
-                // As the item is moved out, the rest of the items are moved up an index.
-                // We always just want to move the first item.
-                th.appendTo(children[0], this.vm.data.parent);
-            }
+
+            this.vm.data.children.slice().forEach((child) =>
+                th.insertBefore(child, this.vm.data)
+            );
```
Comment (jasonvarga) [inline resources/js/components/structures/Branch.vue:140]: Brilliant

**Comment by jasonvarga** [comment]
Thank you!
