### PR TITLE
Throw an exception if collection not found

### LINKED ISSUE #1788: Error message when collection is missing is not clear
## Bug Description

If you have an `entries` fieldtype referencing a non-existent collection and you reference the fieldset in the CP, the error is not very clear.

## How to Reproduce

Make a fieldset (by hand) that has an entries fieldtype w/ a non-existent collection:
```
                    field:
                      type: entries
                      max_items: 1
                      width: 50
                      display: Entry
                      collections:
                        - i-dont-exist
                        - blog
```

## Extra Detail

https://flareapp.io/share/o7Aeqd7p

## Environment

**Statamic version:** 3.0.0-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` (with migrator)

### PR DESCRIPTION
**Pull request by damcclean**
This pull request fixes #1788. It will now throw a `CollectionNotFoundException` when a collection is not found.

### CODE REVIEW

File: src/Fieldtypes/Entries.php [hunk 1]
```diff
@@ -149,8 +150,11 @@ protected function getCreatables()
 
         $collections = $this->getConfiguredCollections();
 
-        return collect($collections)->flatMap(function ($collection) use ($collections) {
-            $collection = Collection::findByHandle($collection);
+        return collect($collections)->flatMap(function ($collectionHandle) use ($collections) {
+            $collection = Collection::findByHandle($collectionHandle);
+
+            throw_if(!$collection, CollectionNotFoundException($collectionHandle));
```
Comment (jasonvarga) [inline src/Fieldtypes/Entries.php:156]: You're missing the `new`.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: src/Fieldtypes/Entries.php (hunk 1 above)
Comment (damcclean) [reply src/Fieldtypes/Entries.php]: Added.

File: src/Fieldtypes/Entries.php [hunk 2]
```diff
@@ -149,8 +150,11 @@ protected function getCreatables()
 
         $collections = $this->getConfiguredCollections();
 
-        return collect($collections)->flatMap(function ($collection) use ($collections) {
-            $collection = Collection::findByHandle($collection);
+        return collect($collections)->flatMap(function ($collectionHandle) use ($collections) {
+            $collection = Collection::findByHandle($collectionHandle);
+
+            throw_if(!$collection, new CollectionNotFoundException($collectionHandle));
```
Comment (jasonvarga) [inline src/Fieldtypes/Entries.php:156]: Really nitpicking now: this should be `! $collection` with a space, to make StyleCI stop complaining and everything pass.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: src/Fieldtypes/Entries.php (hunk 2 above)
Comment (damcclean) [reply src/Fieldtypes/Entries.php]: Done! Gotta keep StyleCI happy.

**Comment by jasonvarga** [comment]
Thank you again
