### PR TITLE
[4.x] Fix entries fieldtype not respecting collection sort column & direction

### LINKED ISSUE #771: RelationshipFieldtype's Selector ignores collection's default sort field
When we configure a relationship field with just one collection of which entries can be "linked", we expect the Selector to use this single collections `sort_by` configuration to be used. Instead, `title` is hardcoded: https://github.com/statamic/three-cms/blob/master/resources/js/components/inputs/relationship/RelationshipInput.vue#L66

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request fixes an issue with the Entries Fieldtype where entries were always ordered by the entry `title`.

This PR will only affect fields where a single collection is configured, otherwise the entries will continue to be ordered by the `title` field.

The fieldtype will use the sort column & sort direction as configured in the collection's YAML file.

Closes #771.

### CODE REVIEW

File: src/Fieldtypes/Entries.php [hunk 1]
```diff
@@ -165,9 +165,9 @@ protected function getFirstCollectionFromRequest($request)
 
     public function getSortColumn($request)
     {
-        $column = $request->get('sort');
+        $column = $request->get('sort', 'title');
 
-        if (! $column && ! $request->search) {
+        if (! $request->sort && ! $request->search && count($this->config('collections')) < 2) {
```
Comment (jasonvarga) [inline src/Fieldtypes/Entries.php:170]: Instead of `$this->config('collections')` use `$this->getConfiguredCollections()`

File: src/Fieldtypes/Entries.php [hunk 2]
```diff
@@ -178,7 +178,7 @@ public function getSortDirection($request)
     {
         $order = $request->get('order', 'asc');
 
-        if (! $request->sort && ! $request->search) {
+        if (! $request->sort && ! $request->search && count($this->config('collections')) < 2) {
```
Comment (jasonvarga) [inline src/Fieldtypes/Entries.php:181]: Ditto

**Review by jasonvarga — CHANGES_REQUESTED** [review]

File: resources/js/components/inputs/relationship/RelationshipInput.vue [hunk 3]
```diff
@@ -69,8 +69,6 @@
                     :selections-url="selectionsUrl"
                     :site="site"
                     :initial-columns="columns"
-                    initial-sort-column="title"
-                    initial-sort-direction="asc"
```
Comment (jasonvarga) [inline resources/js/components/inputs/relationship/RelationshipInput.vue:74]: Removing these lines caused the arrows in the table headers to disappear so you couldn't see which column was being sorted. (Even though it was being sorted correctly.)

**Comment by jasonvarga** [comment]
I pushed up some changes so that the column headers are fixed, and the initial sort/dir are passed through props and can be defined in the fieldtype.

Title ascending is still the default for everything except entries where we override it.

**Review by jasonvarga — APPROVED** [review]
