### PR TITLE
Leverage Laravel to determine secure connection

### LINKED ISSUE #3696: Breadcrumbs aren't working behind reverse proxy
## Bug Description
When you run statamic behind a reverse proxy breadcrumbs no longer generate properly. You only get the Homepage (if you include it) and that's it.
This causes large issues when you deploy statamic in High Availability like on Kubernetes or just alongside many other docker containers with something like https://hub.docker.com/r/jwilder/nginx-proxy in front of it.

I did some investigating and it turns out statamic doesn't respect Forwarded-* headers when determining if a request came over http or over https.

The `URL` Facade returns a http SiteUrl, which in turn produces a mismatch in the `Nav::breadcrumbs()` method. 

#3695 should fix this by simply using Laravel's request class to determine https or http.

## How to Reproduce
Install a fresh statamic/statamic project, configure a nested navigation, configure a reverse proxy to terminate https:// and forward the internal requests to a http:// backend. 
Configure `APP_URL` in `.env` to the https:// address so statamic / Laravel generate most URLs correctly.
Use `{{ nav:breadcrumbs }}`, you'll only see the home link if you chose to `include_home="true"`. 

## Environment

```
Statamic 3.0.49 Pro
Laravel 8.41.0
PHP 7.4.11
optimoapps/statamic-bard-text-align 1.0.2
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by CiiDyR**
We are running statamic behind reverse a reverse proxy to terminate SSL for us before our docker container handles the request.
Currently this makes the URL Facade return a rather useless URL when calling `getSiteUrl`.

Instead of writing custom logic to determine if the original request was https (X-Forwarded-Proto or similar) I think it would make sense to just use Laravels request class to determine this.

Fixes #3696

### CODE REVIEW

**Comment by jasonvarga** [comment]
Awesome. That code was leftover from v2. Nice find.

**Comment by CiiDyR** [comment]
I guess we might as well fully leverage what Laravel offers. If I am not mistaken `$request->root()` should be identical to what would be built in `getSiteUrl()` anyway

**Comment by jasonvarga** [comment]
Yes, maybe. But it should end with a `/`, at least. I see that `root()` wouldn't.

**Comment by CiiDyR** [comment]
I'll take another look at it later. We can at least drop the tenary operator in favor of `getScheme()`.
Maybe that's preferred to just appending a `/`?

**Comment by CiiDyR** [comment]
Took a look at `root()`. Didn't change one bit from 6.x to 8.x. Went with `Str::ensureRight()` just to have it a little more robust.

Instead of Laravel's `root()` we could also use `getSchemeAndHttpHost()` from Symfony which is pretty much identical.

Maybe @jasonvarga can review?

File: src/Facades/Endpoint/URL.php [hunk 1]
```diff
@@ -239,14 +239,10 @@ public function getSiteUrl()
...
+        $rootUrl = app('request')->root();
 
-        $protocol = (! empty(request()->server('HTTPS')) && request()->server('HTTPS') !== 'off' || request()->server('SERVER_PORT') == 443)
-            ? 'https://'
-            : 'http://';
-
-        $domain_name = request()->server('HTTP_HOST').'/';
-
-        return $protocol.$domain_name;
+        return Str::ensureRight($rootUrl);
```
Comment (jasonvarga) [inline src/Facades/Endpoint/URL.php:245]: You didn't pass the slash.

**Review by jasonvarga — CHANGES_REQUESTED** [review]

**Comment by duncanmcclean** [comment]
Just a quick thing, looks like the Style CI checks are failing.. https://github.styleci.io/analyses/BM4g7V?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Review by jasonvarga — APPROVED** [review]
